### ISSUE TITLE
Failed to wildcard re-export in some cases

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#2927] opened 2023-04-25 05:04 UTC
### System Info

  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.49 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/Library/Caches/fnm_multishells/19580_1682235494023/bin/node
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/19580_1682235494023/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 15.6.1

### Details

We are using wildcard re-export to export all methods from `react-router-dom`:

```ts
export * from 'react-router-dom';
```

The `react-router-dom` provides a `useLocation` method, but the method can not be re-exported and there will be an error like this:

```bash
error   TypeError: (0 , i.useLocation) is not a function
    at m (/home/runner/work/modern.js/modern.js/packages/document/main-doc/doc_build/ssr/bundles/main.js:4:317626)
    at eX (/home/runner/work/modern.js/modern.js/packages/document/main-doc/doc_build/ssr/bundles/main.js:1:96905)
    at e (/home/runner/work/modern.js/modern.js/packages/document/main-doc/doc_build/ssr/bundles/main.js:1:98477)
```

If we change the wildcard re-export to named export, then the `useLocation` can be re-exported as expected.

```ts
export { useLocation } from 'react-router-dom';
```

### Reproduce link

https://github.com/web-infra-dev/modern.js

#### Reproduce the error

```bash
git clone git@github.com:web-infra-dev/modern.js.git
git checkout eac19a65400c88323fa0ace1218f5eaad1322f6b
pnpm i
cd packages/document/main-doc
pnpm build
```

After build, we can see the `(0 , i.useLocation) is not a function` error.

#### Using named export

If we open `packages/cli/doc-core/src/runtime/index.ts` and modify the export line:

```diff
- export * from 'react-router-dom';
+ export { useLocation } from 'react-router-dom';
```

```bash
cd packages/cli/doc-core
pnpm build
cd ../../document/main-doc
pnpm build:doc
```

Then the site can be built successfully.

**Comment by IWANABETHATGUY** [comment] 2023-04-25 08:54
The only thing I am sure is that it is not caused by tree shaking: 
I override the rspack config: 
```js
    builderConfig: {
      tools: {
        rspack: {
          optimization: {
            sideEffects: false
          },
          builtins: {
            treeShaking: false
          }
        }
      },
      source: {
        alias: {
          '@components': path.join(__dirname, 'src/components'),
          '@en': path.join(__dirname, 'docs/en'),
          '@zh': path.join(__dirname, 'docs/zh'),
        },
      },
      dev: {
        startUrl: 'http://localhost:<port>/builder/',
      },
    },

```
still emit the error 
![image](https://user-images.githubusercontent.com/17974631/234226015-9129c969-7e2b-49bf-bea0-78db1ab0bd43.png)
further investigation maybe comes later.

**Comment by hyf0** [comment] 2023-06-26 06:46
Close for stale. Please re-open it if you think the issue is not solved.

**Comment by chenjiahan** [comment] 2023-06-26 07:27
I can still reproduce this issue with Rspack 0.2.3, so I will re-open this issue until it is fixed.

![image](https://github.com/web-infra-dev/rspack/assets/7237365/0db47533-57f2-4543-bf1d-aaa53be69047)

**Comment by hardfist** [comment] 2023-07-14 07:55
it seems this is fixed in latest version, can you help check it @chenjiahan

**Comment by chenjiahan** [comment] 2023-07-15 00:17
👍 I will check it later.

**Comment by chenjiahan** [comment] 2023-07-18 11:32
I can reproduce this issue with @rspack/core v0.2.7, so it may not be fixed yet.

![image](https://github.com/web-infra-dev/rspack/assets/7237365/57bf6874-9150-40d2-bab2-2f92977c336b)

**Comment by chenjiahan** [comment] 2023-07-18 14:54
No, it is complex and hard to provide a demo..

**Comment by chenjiahan** [comment] 2023-09-14 00:44
This also breaks the SSG of Modern.js:

![image](https://github.com/web-infra-dev/rspack/assets/7237365/157aa21b-1f10-4826-9931-e0769cee3765)

Reproduce steps:

1. cd modern.js/tests/integration/ssg/fixtures/nested-routes
2. enable Rspack bundler `appTools({ bundler: 'experimental-rspack' })`
3. pnpm run build

**Comment by chenjiahan** [comment] 2023-12-05 03:22
bump

**Comment by hardfist** [comment] 2023-12-05 03:30
@LingyuCoder can you help take a look about this

**Comment by chenjiahan** [comment] 2024-02-03 04:54
bump

**Comment by IWANABETHATGUY** [comment] 2024-02-20 05:55
It looks like it has been fixed in rspack.

**Comment by IWANABETHATGUY** [comment] 2024-02-20 05:55
Feel free to reopen.

**Closed by IWANABETHATGUY** 2024-02-20 05:55 UTC
Labels: bug, team
