### ISSUE TITLE
`builtins.define` not support dynamic process.env.NODE_ENV?

### ISSUE THREAD

**Issue by southorange0929** [web-infra-dev/rspack#3489] opened 2023-06-09 02:23 UTC
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 218.88 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.volta/tools/image/node/16.18.0/bin/node
    npm: 8.19.2 - ~/.volta/tools/image/node/16.18.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Firefox: 113.0.2
    Safari: 16.4
  npmPackages:
    @rspack/cli: ^0.2.1 => 0.2.1 

### Details

```js
module.exports = {
	builtins: {
		html: [
			{
				template: "./index.html"
			}
		],
		define: {
			      "process.env.NODE_ENV": process.env.NODE_ENV
		}
	},
};
```

I add `process.env.NODE_ENV` with document,but it crased some errors.
https://www.rspack.dev/zh/config/builtins.html#builtinsdefine

<img width="808" alt="image" src="https://github.com/web-infra-dev/rspack/assets/32590310/10393074-482a-42c6-96e2-b61d6e2e4b5c">

### Reproduce Steps

```shell
npx create rspack@latest
pnpm i && pnpm run dev
```

**Comment by southorange0929** [comment] 2023-06-09 02:56
Looks like `define` is not working? Or is it difference with `webpack.DefinePlugin`?

I tried another variable,but got `undefined` with `console.log(window.xxx)`
```ts
    define: {
	  xxx: "123"
    },
```

**Comment by hyf0** [comment] 2023-06-09 02:58
With your config, code below

```js
console.log(process.env.NODE_ENV)
``` 

would be transformed into

```js
console.log(devlopement)
```

Use

```js
module.exports = {
	builtins: {
		html: [
			{
				template: "./index.html"
			}
		],
		define: {
			      "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV)
		}
	},
};
```

instead.

**Comment by hyf0** [comment] 2023-06-09 03:01
> Looks like `define` is not working? Or is it difference with `webpack.DefinePlugin`?
> 
> I tried another variable,but got `undefined` with `console.log(window.xxx)`
> 
> ```ts
>     define: {
> 	  xxx: "123"
>     },
> ```

`builtins.define` is doing replacements in compile-time not `window.xxx = xxx`. This is expected.

I'm going to close this issue for this is not a bug.

**Closed by hyf0** 2023-06-09 03:01 UTC
Labels: question

**Comment by hyf0** [comment] 2023-06-09 03:05
> That's my fault.Thanks a lot

There are no faults on anyone. We are welcome to be asked any questions in issue, discussion, or Discord :).
