### ISSUE TITLE
webpack-retry-chunk-load-plugin using deprecated mainTemplate hook

### ISSUE THREAD

**Issue by psylaux** [web-infra-dev/rspack#4602] opened 2023-11-10 01:54 UTC
### Alternative for webpack-retry-chunk-load-plugin

# 
I am using this retry chunk plugin, which retries loading when a chunk fails to load. This is the plugin [here](https://www.npmjs.com/package/webpack-retry-chunk-load-plugin?activeTab=readme)

This particular plugin is using the mainTemplate hook, which I see is deprecated and will not be supported in rspack. Are there any work arounds for this functionality or any other plugins that can be used in place of this?

**Comment by chenjiahan** [comment] 2023-11-10 03:36
There is an alternative: use Rsbuild and Rsbuild's Assets Retry plugin.

- https://rsbuild.dev/
- https://rsbuild.dev/plugins/list/plugin-assets-retry.html

Note that Assets Retry plugin currently cannot work on dynamically imported chunks. This feature will be supported in the future.

**Comment by psylaux** [comment] 2023-11-20 03:25
Hi, Is this alternative compatible with existing projects? From what I understand, I would need to replace my current builder with rsbuild to use the plugins, is that right?

**Comment by chenjiahan** [comment] 2023-11-20 03:32
Yes, you should move to Rsbuild first. And Rsbuild has provided some migration guides, such as https://rsbuild.dev/guide/migration/cra.html

**Comment by psylaux** [comment] 2023-11-20 03:38
Ah okay, my team wouldn't be open to changing our builder, but thank you for this suggestion!

**Comment by pushkargupta9807** [comment] 2023-11-28 04:41
Are there any plans to support the mainTemplate hook sometime soon? Switching to rsbuild for this plugin seems like an overkill. 

Is there any other alternative with rspack to inject code in the main Template? 
cc: @hardfist

**Comment by hardfist** [comment] 2024-07-23 03:17
duplicate of https://github.com/web-infra-dev/rspack/issues/6837, you can track here

**Closed by hardfist** 2024-07-23 03:17 UTC
Labels: tracking issue
