### ISSUE TITLE
[Bug]: Panic occurred at runtime

### ISSUE THREAD

**Issue by khangviet1996** [web-infra-dev/rspack#7194] opened 2024-07-17 01:19 UTC
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 4.00 GB / 31.87 GB
  Browsers:
    Chrome: 126.0.6478.127
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.19041.4355  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 4.00 GB / 31.87 GB
  Browsers:
    Chrome: 126.0.6478.127
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.19041.4355
```

### Details
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Could not find asset by name: "static/svg/services_icon.92cdc6a8.svg"
Location: crates\rspack_core\src\stats.rs:25

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: napi_register_module_v1
    at <unknown source file>
 2: napi_register_module_v1
    at <unknown source file>
 3: napi_register_module_v1
    at <unknown source file>
 4: napi_register_module_v1
    at <unknown source file>
 5: wasmer_vm_f64_nearest
    at <unknown source file>
 6: napi_register_module_v1
    at <unknown source file>
 7: napi_register_module_v1
    at <unknown source file>
 8: napi_register_module_v1
    at <unknown source file>
 9: napi_register_module_v1
    at <unknown source file>
10: napi_register_module_v1
    at <unknown source file>
11: napi_register_module_v1
    at <unknown source file>
12: napi_register_module_v1
    at <unknown source file>
13: napi_register_module_v1
    at <unknown source file>
14: napi_register_module_v1
    at <unknown source file>
15: napi_register_module_v1
    at <unknown source file>
16: napi_register_module_v1
    at <unknown source file>
17: napi_register_module_v1
    at <unknown source file>
18: napi_register_module_v1
    at <unknown source file>
19: napi_register_module_v1
    at <unknown source file>
20: napi_register_module_v1
    at <unknown source file>
21: wasmer_vm_f64_nearest
    at <unknown source file>
22: napi_register_module_v1
    at <unknown source file>
23: napi_register_module_v1
    at <unknown source file>
24: napi_register_module_v1
    at <unknown source file>
25: BaseThreadInitThunk
    at <unknown source file>
26: RtlUserThreadStart
    at <unknown source file>
 ELIFECYCLE  Command failed with exit code 3221226505.
 
 After  I upgraded to ^1.0.1-beta.2, I'm facing this issue

### Reproduce link

No response

### Reproduce Steps
```pnpm run dev```
Unfortunately, I don't have any reproducible example, because this is a big company's private project. I'm facing same issue https://github.com/web-infra-dev/rspack/issues/7169https://github.com/web-infra-dev/rspack/issues/7169

**Comment by chenjiahan** [comment] 2024-07-17 05:52
I have reproduced this issue:

![image](https://github.com/user-attachments/assets/dbbd9700-75e8-4d87-9fc7-7dbd631829be)

1. https://github.com/web-infra-dev/rsbuild/tree/main/website
2. pnpm dev
3. update `website/theme/index.tsx`
4. panic occurred

**Comment by matteom-synth** [comment] 2024-07-17 06:56
Yeah, I thought it was fixed in #7169 but the issue is still there for me too. If you need another data point:

### System Info

```
  System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 3.25 GB / 36.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.19.0 - ~/.local/share/nvm/v18.19.0/bin/node
    npm: 10.2.3 - ~/.local/share/nvm/v18.19.0/bin/npm
  Browsers:
    Chrome: 126.0.6478.127
    Firefox Developer Edition: 128.0
    Safari: 17.5
```

### Details

```
  Rsbuild v1.0.0-alpha.6

● web ━━━━━━━━━━━━━━━━━━━━━━━━━ (70%) sealing chunk ids                                                                                                                             Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  assertion failed: self.max_target_is_set
Location: crates/rspack_core/src/exports_info.rs:1722

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _napi_register_module_v1
    at <unknown source file>
 6: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 7: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: _napi_register_module_v1
    at <unknown source file>
12: _napi_register_module_v1
    at <unknown source file>
13: _napi_register_module_v1
    at <unknown source file>
14: _napi_register_module_v1
    at <unknown source file>
15: _napi_register_module_v1
    at <unknown source file>
16: _napi_register_module_v1
    at <unknown source file>
17: _napi_register_module_v1
    at <unknown source file>
18: _napi_register_module_v1
    at <unknown source file>
19: _napi_register_module_v1
    at <unknown source file>
20: _napi_register_module_v1
    at <unknown source file>
21: _napi_register_module_v1
    at <unknown source file>
22: _napi_register_module_v1
    at <unknown source file>
23: _napi_register_module_v1
    at <unknown source file>
24: _napi_register_module_v1
    at <unknown source file>
25: _napi_register_module_v1
    at <unknown source file>
26: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
27: _napi_register_module_v1
    at <unknown source file>
28: _napi_register_module_v1
    at <unknown source file>
29: _napi_register_module_v1
    at <unknown source file>
30: _napi_register_module_v1
    at <unknown source file>
31: __pthread_joiner_wake
    at <unknown source file>
fish: Job 1, 'pnpm studio rsbuild:build' terminated by signal SIGABRT (Abort)
```

### Reproduce link

_No response_

### Reproduce Steps

Unfortunately, I don't have any reproducible link/example, since this is our company's app, in a big monorepo. For what is worth, we're building other packages successfully, and the `rsbuild dev`, using the same config I'm using here, is working fine.

The interesting bit here is that re-running the build script multiple times does solve the issue sometimes. 

Let me know if I can provide any additional detail to debug it further.

```
    "@rsbuild/core": "1.0.0-alpha.6",
    "@rsbuild/plugin-react": "1.0.0-alpha.6",
    "@rsbuild/plugin-svgr": "1.0.0-alpha.6",
    "@rsbuild/plugin-type-check": "1.0.0-alpha.6",
```

**Comment by kamalbennani** [comment] 2024-07-17 09:00
I'm actually facing the same issue as we are in the process of moving from CRA to Rsbuild.

We are using the latest version of all the libs:
    "@rsbuild/core": "1.0.1-beta.2",
    "@rsbuild/plugin-react": "1.0.1-beta.2",
    "@rsbuild/plugin-svgr": "1.0.1-beta.2",
    "@rsbuild/plugin-sass": "1.0.1-beta.2",

![Screenshot 2024-07-17 at 10 59 02](https://github.com/user-attachments/assets/b9c34e44-28d1-4a41-8e03-e616a6653f53)

**Comment by LingyuCoder** [comment] 2024-07-17 10:45
fixed by https://github.com/web-infra-dev/rspack/pull/7197, please upgrade to v1.0.0-alpha.5

**Closed by LingyuCoder** 2024-07-17 10:45 UTC
