### ISSUE TITLE
即使配置了  target: ['web', 'es2020'],打包不会报错,但是运行在浏览器会禁用使用顶层await 语法 

### ISSUE THREAD

**Issue by hanyaxxx** [web-infra-dev/rspack#3898] opened 2023-08-03 15:44 UTC
### What problem does this feature solve?

  target: ['web', 'es2020'], 

### What does the proposed API of configuration look like?

Support top-level await

**Comment by hyf0** [comment] 2023-08-04 03:25
我们还没支持  top-level await. Duplicate of https://github.com/web-infra-dev/rspack/issues/3889.

**Closed by hyf0** 2023-08-04 03:25 UTC
Labels: feat, duplicated
