### ISSUE TITLE
[Bug]: Strange HMR bug after removing `<style>` in Vue SFC

### ISSUE THREAD

**Issue by ZhangTaibin** [web-infra-dev/rspack#7805] opened 2024-09-05 06:59 UTC
### Version

```sh
System: Window
Browser: Edge
vue: 2/3
and others node js 18/20
```

### Details

i just create a pure project with `pnpm create rsbuild@latest`. 

And then run the project with `pnpm run dev` . it's ok and i dont edit anything. 

when i delete `<style></style` element in `App.vue`. It will throw an error writting "Cannot read properties of undefined (reading 'call')". Then i stop the HMR and run the project again. It will be OK.

I think that it has some strange problem with HMR

### Reproduce link

not link

### Reproduce Steps

pnpm create rsbuild@latest

cd project

pnpm i

pnpm run dev

delete style element in `App.vue`

**Comment by CPunisher** [comment] 2024-09-10 08:25
i cant reproduce with rspack.
after debugging with rsbuild, I find vue style query triggers vue-loader before the vue file does, which is difference from the correct orders in rspack. The vue loader throws errors since there is no style block in the descriptor when handling the style query.

**Comment by CPunisher** [comment] 2024-09-16 04:01
I reproduce with the following rspack config:
```js
const rspack = require('@rspack/core');
const { VueLoaderPlugin } = require('vue-loader');

/** @type {import('@rspack/cli').Configuration} */
const config = {
  entry: './src/index.js',
  plugins: [
    new VueLoaderPlugin(),
    new rspack.HtmlRspackPlugin({}),
    new rspack.CssExtractRspackPlugin({
      runtime: false,
    }),
  ],
  // experiments: {
  //   css: true,
  // },
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [
          { loader: rspack.CssExtractRspackPlugin.loader, options: {} },
          'css-loader',
        ],
        type: 'javascript/auto',
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          // Note, for the majority of features to be available, make sure this option is `true`
          experimentalInlineMatchResource: true,
        },
      },
    ],
  },
};
module.exports = config;
```

My guess of about the process:
CssExtractRspackPlugin loader calls `this.importModule`, which introduce an extra module that derives from the css module generated by vue-loader (`App.vue?type=style`). This extra module is handled by `ModuleExecutor`. When the style block in the vue file is removed, rspack calls `ModuleExecutor::hook_before_make` to rebuild the extra module before rebuilding  others. When vue-loader processes the extra module, error is thrown since there is no style block in the vue descriptor.

**Comment by hardfist** [comment] 2024-09-16 04:09
this should be fixed in https://github.com/web-infra-dev/rspack/pull/7878 and released in 1.0.5, @CPunisher can you help verify it

**Comment by hardfist** [comment] 2024-09-16 14:59
@ZhangTaibin please try 1.0.5

**Comment by ZhangTaibin** [comment] 2024-09-19 01:51
1、It' OK with project creating by `pnpm create rspack@latest`

**Comment by ZhangTaibin** [comment] 2024-09-19 01:58
It' done when use `Rspack CLI` to create project. 

When use `rsbuild@1.0.4` to create project. If i change CSS content, it's done. 

But it's not done When i delete `<style></style>` tag or clear all CSS content. Throw error `Cannot read properties of undefined (reading 'content')`

System: Windows 11

**Comment by 9aoy** [comment] 2024-09-20 06:50
> delete style tag  & throw `Cannot read properties of undefined (reading 'content')` error in Rsbuild 1.0.4 

+1. It can also be reproduced in the rsbuild example. 

https://github.com/web-infra-dev/rsbuild/tree/main/examples/vue

**Comment by ZhangTaibin** [comment] 2024-11-20 03:42
Rspack Cli is done. But Rsbuild is not done.

This use Rsbuild:
![Image](https://github.com/user-attachments/assets/237c8cff-d437-4fa0-a8cf-0844fce23c4b)

This use Rspack Cli:
![Image](https://github.com/user-attachments/assets/a768cd8d-d3bc-415b-b8b8-c0b97ca55c55)

**Comment by CPunisher** [comment] 2024-11-28 04:39
Let's say module A imports module B by one of A's loaders with `importModule`:
In the initial build, when A is being built, B is executed so everything is ok.
In the hmr rebuild, B is being rebuilt before A by the following code. But actually B should not be built since there's no style block in A. https://github.com/web-infra-dev/rspack/blob/30509316e514e50768ffa86169026769a8b468f9/crates/rspack_core/src/compiler/module_executor/mod.rs#L68

I come up with 3 solutions:
1. Add undefined checks for `vue-loader`, which is the most easy way.
2. Merge the executor artifact into the main artifact. This solution was once rejected.
3. Do not rebuild B ahead. Instead, let A introduce B again. I'm not sure this solution introduces other problems.

**Closed** 2024-12-07 04:49 UTC
Labels: bug
