### ISSUE TITLE
[Bug]: Angular bundle size 2x bigger than with Webpack

### ISSUE THREAD

**Issue by edbzn** [web-infra-dev/rspack#6436] opened 2024-05-02 12:51 UTC
### System Info

 System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 25.70 GB / 30.98 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.1 - /usr/local/bin/pnpm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 121.1.62.165
    Chrome: 121.0.6167.184
  npmPackages:
    @rspack/cli: ^0.6.3 => 0.6.3 
    @rspack/core: ^0.6.3 => 0.6.3 

### Details

Hi,

I'm trying Rspack with Angular, and all the critical features seem to be working. However, the bundle size generated by Rspack is 2x bigger than base builders. Here's the [configuration](https://github.com/edbzn/ng-rspack/blob/main/rspack.config.js) I'm using. The generated main.js file is around 421K in my example against around 250K for Webpack or Esbuild. You can see the build logs [here](https://github.com/edbzn/ng-rspack/blob/main/build.log#L766). Do you have an idea why, and how I can get approximatively the same bundle size?

Thanks!

### Reproduce link

https://github.com/edbzn/ng-rspack/blob/main

### Reproduce Steps

Rspack bundle size: 

```
pnpm nx build && ls -lah dist/ng-rspack/rspack
```

Webpack bundle size: 

```
pnpm nx build-wp && ls -lah dist/ng-rspack/webpack
```

**Comment by hardfist** [comment] 2024-07-01 14:16
bump

**Comment by hardfist** [comment] 2024-07-01 14:21
@edbzn after https://github.com/web-infra-dev/rspack/pull/6888 merged, rspack output seems smaller than angular now, can you help check the result using  1.0.0-alpha.0

**Comment by edbzn** [comment] 2024-07-02 07:59
@hardfist I updated the repo with rspack 1.0.0-alpha.0 and the bundle size goes down from 488K to 468K, still almost twice the size as webpack or esbuild. However Angular has a custom [JavaScriptOptimizerPlugin](https://github.com/angular/angular-cli/blob/355ae1a58f10e3ec5f1a5e131c884dca17599efc/packages/angular_devkit/build_angular/src/tools/webpack/configs/common.ts#L298) and [DedupeModulePlugin](https://github.com/angular/angular-cli/blob/355ae1a58f10e3ec5f1a5e131c884dca17599efc/packages/angular_devkit/build_angular/src/tools/webpack/plugins/dedupe-module-resolve-plugin.ts#L44) that I haven't configured in my rspack config, could it be the cause? I wanted to rely on the rspack `SwcJsMinimizerRspackPlugin` instead.

**Comment by hardfist** [comment] 2024-07-02 09:53
@edbzn  the size diff is actually caused by rspack doesn't use `JavaScriptOptimizerPlugin` while webpack does, 
after align optimization with webpack, their size are nearly the same

**Comment by ChristofFritz** [comment] 2024-07-02 10:09
What's the build-time difference? We have a huge angular project and I might try rspack on it

**Comment by edbzn** [comment] 2024-07-02 10:26
Thanks @hardfist, I think this issue can be closed.

**Closed** 2024-07-02 10:33 UTC
Labels: bug, pending triage
