### ISSUE TITLE
Support package.json exports "Alternatives"

### ISSUE THREAD

**Issue by puehringer** [web-infra-dev/rspack#5052] opened 2023-12-18 13:19 UTC
### What problem does this feature solve?

webpack supports _Alternatives_ in package.json#exports fields: https://webpack.js.org/guides/package-exports/#alternatives

This allows us to import from one path, if possible, and fallback to another path if required. Currently in rspack, this will fail with a `Failed to resolve` in case the first occurance (`./dist/index.js`) does not exist. It works in webpack however. 

```json
  "exports": {
    ".": {
      "types": [
        "./dist/index.d.ts",
        "./src/index.ts"
      ],
      "import": [
        "./dist/index.js",
        "./src/index.ts"
      ]
    }
  }
```

### What does the proposed API of configuration look like?

No API required.

**Comment by Boshen** [comment] 2023-12-18 14:04
Do you have a real package json with real use case for me to test on?

**Comment by puehringer** [comment] 2023-12-18 14:31
Hi @Boshen, I can't make our repository available, but I created a minimal reproducible demo: [rspack_export_alternatives.zip](https://github.com/web-infra-dev/rspack/files/13704956/rspack_export_alternatives.zip)

Instructions are in the README.md (and pasted here): 

`lib` contains the library to install, with `exports` pointing to `dist` and `src`. 

`app` is consuming this library (installed via portal). 

To reproduce, do the following: 

```
cd app
yarn
yarn build
```

This will work and create a `app/dist/main.js` with content `Hello from dist`. 

Now, remove the `lib/dist/lib.js` file. webpack would now fallback to the `lib/src/lib.ts` file, but rspack fails with "Failed to resolve lib in ...". 


Let me know if you need anything else, and thanks for getting back to me so quickly!

**Comment by Boshen** [comment] 2023-12-19 04:44
I know this day will come when I was implementing this feature, but no this soon - because I found a discrepancy / compatibility issue between the implementations between webpack/enhanced-resolve and node.js ESM.

This is going to be a long explanation detailing what's going on with this feature, please bear with me.

---

Let's start with the [X/Y problem](https://xyproblem.info/): 

# The `Y` problem

What you are actually trying to do is:

* bundle the source `.ts` code during development
* bundle the js code when it's shipped to your private registry for others to consume
 
This situation comes from the fact that we are importing the package inside our monorepo via `workspace: *`. The transpiled `.js` file is obviously not there for the imported packaged in our development workflow, so we eventually look for ways to import the `.ts` file and bundle from source instead.

I've seen this situation at ByteDance for all of our monorepos, and the solution we have settled on is using tsconfig paths + changing the `resolve.extensions` option to accept the `.ts` extention ([the default](https://www.rspack.dev/config/resolve.html#resolveextensions) in Rspack). This is a solution asked by the community and is offered in the [tsconfig-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin).

Rspack (`oxc_resolver` as the module resolver) has provided built-in support for this feature as documented [here](https://www.rspack.dev/config/resolve.html#resolvetsconfig).

# The `X` Problem

What should be the correct behavior for `exports` array (alternatives)?

Given the module `/node_modules/foo` with the following package.json:

```json
{
  "name": "foo",
  "exports": {
     "./bar": ["bad-specifier", "./non-existent.js", "./existent.js"]
  }
}
```

and `require("foo/bar")`:

`webpack/enhanced-resolve` returns `"/node_modules/foo/existent.js"`.

node.js returns `Error: Cannot find module '/node_modules/foo/non-existent.js'`.

The node.js behavior is backed by the specification stated in [Resolution Algorithm Specification](https://nodejs.org/api/esm.html#resolution-algorithm-specification):

```
PACKAGE_TARGET_RESOLVE(packageURL, target, patternMatch, isImports, conditions)
...
3. Otherwise, if target is an Array, then
...
  2. For each item targetValue in target, do
    1. Let resolved be the result of PACKAGE_TARGET_RESOLVE( packageURL, targetValue, patternMatch, isImports, conditions), continuing the loop on any Invalid Package Target error.
```

Notice the statement `continuing the loop on any Invalid Package Target error`, it is not "Not Found Error".

As for webpack, the [documentation](https://webpack.js.org/guides/package-exports/#alternatives) states the following:

> Instead of providing a single result, the package author may provide a list of results. In such a scenario this list is tried in order and the first valid result will be used.

It is hinting that it will try the values in order not matter what the error is, and return the successful one. This is backed by testing the enhanced-resolve implementation.

---

I don't know how to deal with this situation so I'm going to call the experts here.

Best Regards,

Boshen.

**Comment by Boshen** [comment] 2023-12-19 05:10
Andrew [replied](https://twitter.com/atcb/status/1736976463470137795):

> As for loading TS files in development, I use conditional exports for that [https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/3f5e05f5a40ef117874430cb226b0088ee7233ae/packages/core/package.json#L29](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/3f5e05f5a40ef117874430cb226b0088ee7233ae/packages/core/package.json#L29)

**Comment by hardfist** [comment] 2023-12-19 06:52
https://github.com/nodejs/node/issues/37928#issuecomment-808833604 It's a known issue in Node.js side and It seems Node.js current behavior is not useful for real world application and Webpack and Typescript all choose fallback style, so It seems following enhanced-resolve's way is better for Rspack.
@andrewbranch But I'm not sure Typescript choose fallback style is a feature or bug?

**Comment by andrewbranch** [comment] 2023-12-19 16:29
For TypeScript, it’s a bug when it happens in `--moduleResolution nodenext` (https://github.com/microsoft/TypeScript/issues/50762). If you’re in `--moduleResolution bundler`, I guess it’s a feature 😄

**Comment by hardfist** [comment] 2023-12-19 16:46
> For TypeScript, it’s a bug when it happens in `--moduleResolution nodenext` ([microsoft/TypeScript#50762](https://github.com/microsoft/TypeScript/issues/50762)). If you’re in `--moduleResolution bundler`, I guess it’s a feature 😄

that is interesting，@alexander-akait sorry to bother you，I am also not sure whether webpack current fallback strategy is a feature or bug，or is aligning resolve algorithm with Node.js is a goal of enhanced-resolve？

**Comment by alexander-akait** [comment] 2023-12-20 17:20
That's intresting, especial https://github.com/nodejs/node/issues/37928#issuecomment-808833604, I want to say it is not a bug, the fallback style is useful and provide more power

> 1. Let resolved be the result of PACKAGE_TARGET_RESOLVE( packageURL, targetValue, patternMatch, isImports, conditions), continuing the loop on any Invalid Package Target error.

We literally read it as - if you get an error then continue

https://github.com/nodejs/node/issues/37928#issuecomment-808833604

> Exports is generally designed to resolve unambiguously without hitting the disk. So what you're observing is working as intended: As soon as we find a valid file name, we assume that it's the intended target. It explicitly doesn't matter if the file currently exists or not. E.g. it would be valid to resolve to a non-existing path, create the file, and then load it.

I disagree with that, because what's the point using an array of alternatives if we will take the first target.

I think this sentence explains the logic pretty clearly (https://github.com/nodejs/node/issues/37928):

> Fallback arrays allow validation failures to continue checking the next item in the fallback array providing forwards compatiblitiy for new features in future based on extending these validation rules to new cases.

**Comment by hardfist** [comment] 2023-12-21 15:44
@alexander-akait thanks for your detail explanation,  @Boshen since Typescript(moduleResolution set to `bundler`) and Webpack has the same behavior(choose fallback), It seems we should align this behavior with enhanced-resolve other than Node.js current behavior.

**Comment by Boshen** [comment] 2023-12-22 03:31
Given this [twitter thread](https://twitter.com/atcb/status/1736987593534034184) and my understanding of future compatibility, my advice is also **do not use export arrays**.

Remember, packages are published to public / private npm registries, any thing that do not conform to the specification will break future compatibility. It does not matter whether the given feature is useful or not.

As for alternative solutions to what I believe what the actual problem is, we have:

1. use tsconfig paths alias
2. use conditional exports https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/3f5e05f5a40ef117874430cb226b0088ee7233ae/packages/core/package.json#L29

**Comment by alexander-akait** [comment] 2023-12-22 12:31
It might be useful to ping someone from the Node.js team here because I want to hear the real reason why it was implemented this way

**Comment by Boshen** [comment] 2024-03-29 02:52
Closing due to lack of actionable items. 

Please see all the linked issues in https://github.com/bluwy/publint/issues/92

**Comment by yf-yang** [comment] 2024-06-14 14:52
@Boshen 
Hi, I tried to follow your advice on the monorepo, but I can't get it to work. Would you mind taking a look and explaining what to do in detail?


> the solution we have settled on is using tsconfig paths + changing the resolve.extensions option to accept the .ts extention ([the default](https://www.rspack.dev/config/resolve.html#resolveextensions) in Rspack)

reproduction:
https://github.com/yf-yang/modern-js-examples/tree/resolve-ts

Brief:
- There is one modernjs app repo and a `dep` repo. `pnpm` is the package manager and it uses `"dep": "workspace:^"` as the dependency. 
- Project reference is set in `app`'s tsconfig.
- If set `"exports": "src/index.ts"` in `dep`'s package.json, it works.
- If remove `"exports": "src/index.ts"` in `dep`'s package.json, then configure `app`'s `modern.config.js`:
``` javascript
tools: {
    rspack: config => {
      config.resolve = {
        ...(config.resolve ?? {}),
        tsConfig: {
          configFile: path.resolve(__dirname, './tsconfig.json'),
          references: 'auto',
        },
      };
      return config;
    }
}
```
Then the dev server fails to resolve the dependency.

I think I missed some points here. Thank you for your advice!

**Comment by yf-yang** [comment] 2024-06-14 17:40
Sure
I just found a doc in modernjs
https://modernjs.dev/en/guides/advanced-features/source-build.html

I'll give it a try and then create another issue if stuck. Thank you for your attention

**Comment by hardfist** [comment] 2024-06-17 06:18
@yf-yang we are reconsidering support this feature

**Comment by hardfist** [comment] 2024-08-13 06:32
since webpack deprecate alternative now, Rspack's current behavior is same as latest webpack

**Closed** 2024-08-13 06:33 UTC
Labels: feat, A-resolver
