### ISSUE TITLE
[Bug]: Panic occurred at runtime. Message: content should be available

### ISSUE THREAD

**Issue by krutoo** [web-infra-dev/rspack#5938] opened 2024-03-14 05:10 UTC
### System Info

```
  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 25.24 GB / 31.21 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.2 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.128
  npmPackages:
    @rspack/cli: ^0.5.7 => 0.5.7 
    @rspack/core: ^0.5.7 => 0.5.7 
```

### Details

```
> rspack --watch

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  content should be available
Location: /build/crates/rspack_loader_runner/src/runner.rs:399

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                               ⋮ 1 frame hidden ⋮                               
 2: __GI___clone3
    at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
Aborted (core dumped)

```

### Thoughs

Maybe this is because package (`@sima-land/isomorph`) uses exports field

### Reproduce link

https://github.com/krutoo/isomorph-bun-vs-node

### Reproduce Steps

1. clone repo https://github.com/krutoo/isomorph-bun-vs-node
2. `npm install`
3. `npm run dev`
4. see error during build

**Comment by h-a-n-a** [comment] 2024-03-14 06:17
I was not able to reproduce this panic locally. Here's what I get:

```
❯ npm run build

> isomorph-bun-vs-node@0.0.0 build
> rspack

ERROR in ./src/pages/authors/index.tsx
  × Package subpath './preset/node-handler' is not defined by "exports" in /Users/bytedance/Projects/rspack-issue-reproduce/isomorph-bun-vs-node/node_modules/@sima-land/isomorph/package.json


ERROR in ./src/pages/posts/index.tsx
  × Package subpath './preset/node-handler' is not defined by "exports" in /Users/bytedance/Projects/rspack-issue-reproduce/isomorph-bun-vs-node/node_modules/@sima-land/isomorph/package.json


Rspack compiled with 2 errors in 972 ms
```

**Comment by krutoo** [comment] 2024-03-14 07:39
@h-a-n-a I dont see errors like on your case, do you use ubuntu?

**Comment by krutoo** [comment] 2024-03-14 07:44
@h-a-n-a can you make `cat ./node_modules/@sima-land/isomorph/package.json | grep node-handler`?

Because this export is defined in `package.json`

**Comment by xc2** [comment] 2024-03-14 16:07
@krutoo please provide the `sima-land-isomorph-0.0.0.tgz` file. 

public version of [@sima-land/isomorph](https://www.npmjs.com/package/@sima-land/isomorph?activeTab=code) has no exports related to node-handler

**Comment by krutoo** [comment] 2024-03-14 16:23
> @krutoo please provide the `sima-land-isomorph-0.0.0.tgz` file. 
> 
> 
> 
> public version of [@sima-land/isomorph](https://www.npmjs.com/package/@sima-land/isomorph?activeTab=code) has no exports related to node-handler

Folder "./tgz" in repo (sorry for wrong path in package.json

**Comment by xc2** [comment] 2024-03-14 16:59
just tried ubuntu 20.04(x86_64) and debian bookworm(arm64) with no luck.

weird

**Comment by krutoo** [comment] 2024-03-14 17:42
@xc2 @h-a-n-a i found that it was my stashed code

try this branch please
https://github.com/krutoo/isomorph-bun-vs-node/tree/rspack-panic

**Comment by xc2** [comment] 2024-03-15 02:41
thanks @krutoo it reproduces.

it is caused by code below

```js
import( /* webpackIgnore: true */ `bun:jsc`)
```

swc will transform it into `import("bun:jsc");` by default when the request is in template literals. [playground](https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA8vMLcgvKtFQ0NdSKE9NKkhMzvZMz8svSrVSKCkqTVXQ0ldISCrNs8oqTk7Q5AIAgs4vUi0AAAA%3D&config=H4sIAAAAAAAAA6vmUlBQyipOVrJSqAYyIUCpILGoOLUIRQwoWlyZV5JYARRVSk3OTSxOLsosKFGCK6jV4QKza7lqAazb4S9VAAAA)

there're two approach to avoid:

1. modify it to `import( /* webpackIgnore: true */ "bun:jsc")`: [playground](https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA8vMLcgvKtFQ0NdSKE9NKkhMzvZMz8svSrVSKCkqTVXQ0ldQTyrNs8oqTlbX5AIAq1mJ2C0AAAA%3D&config=H4sIAAAAAAAAA6vmUlBQyipOVrJSqAYyIUCpILGoOLUIRQwoWlyZV5JYARRVSk3OTSxOLsosKFGCK6jV4QKza7lqAazb4S9VAAAA)
2. or turn `jsc.preserveAllComments` on for `builtin:swc-loader`: [playground](https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA8vMLcgvKtFQ0NdSKE9NKkhMzvZMz8svSrVSKCkqTVXQ0ldISCrNs8oqTk7Q5AIAgs4vUi0AAAA%3D&config=H4sIAAAAAAAAA6vmUlBQyipOVrJSqAYyIUCpILGoOLUIRQwoWlyZV5JYARRVSk3OTSxOLsosKFGCK6jVQdJflArUX5bqmJPjnJ%2Bbm5pXUgzUVlJUmgpWU8tVCwAnrAxReAAAAA%3D%3D)

#5775 this issue will also help

**Comment by krutoo** [comment] 2024-03-15 05:41
@xc2 thanks a lot but why string literal change the behavior?

**Comment by h-a-n-a** [comment] 2024-03-15 20:24
> @xc2 thanks a lot but why string literal change the behavior?

@krutoo That's not expected for us. We will fix this. ;-)

**Comment by krutoo** [comment] 2024-05-16 04:38
bump

**Comment by h-a-n-a** [comment] 2024-06-25 12:36
This was fixed in DefinePlugin refactor.

**Closed by h-a-n-a** 2024-06-25 12:36 UTC
Labels: bug
