### ISSUE TITLE
在 build 时，NODE_ENV 为 build，之前版本是 production，这个改动是有意设计的还是 BUG ？

### ISSUE THREAD

**Issue by nashaofu** [web-infra-dev/rspack#2628] opened 2023-04-06 03:02 UTC
https://github.com/web-infra-dev/rspack/blob/860bf43a3ee361d3e7bb1d3a4bd83ecf6aea4a0b/packages/rspack-cli/src/rspack-cli.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L37-L41

在运行 serve 与 build 时，在 rspack.config.js 中使用 process.env.NODE_ENV，发现值为 `serve` 与 `build`

**Comment by hyf0** [comment] 2023-04-06 03:08
Thanks for reporting. I think it's a bug and was reported in #2616. We would fix it before the next minor release.

I would close this issue due to this is a duplicate of #2616.

---

感谢反馈。我认为这是一个 bug， 已经在 #2616 中报告过了。我们将在下一次小版本发布前修复它。我将关闭这个 issue ，因为我们已经有 #2616 了。

**Closed by hyf0** 2023-04-06 03:08 UTC
Labels: needs-triage, duplicated
