### ISSUE TITLE
[Bug]: HMR fails with RSPack v0.7.1

### ISSUE THREAD

**Issue by markmssd** [web-infra-dev/rspack#6740] opened 2024-06-05 17:49 UTC
### System Info

MacOS 14.4.1

### Details

With RSPack v0.7.1, HMR seems to have issues. Here is the stack trace:

```
app1 start: Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
app1 start: Message:  should have module graph module
app1 start: Location: crates/rspack_core/src/module_graph/mod.rs:563
app1 start: Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
app1 start: Run with RUST_BACKTRACE=full to include source snippets.
app1 start: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
app1 start:  1: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start:  2: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start:  3: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start:  4: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start:  5: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start:  6: _wasmer_vm_imported_memory32_atomic_notify
app1 start:     at <unknown source file>
app1 start:  7: _wasmer_vm_imported_memory32_atomic_notify
app1 start:     at <unknown source file>
app1 start:  8: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start:  9: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 10: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 11: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 12: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 13: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 14: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 15: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 16: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 17: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 18: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 19: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 20: _napi_register_module_v1
app1 start:     at <unknown source file>
app1 start: 21: __pthread_joiner_wake
app1 start:     at <unknown source file>
```

<img width="938" alt="Screenshot 2024-06-05 at 1 43 00 PM" src="https://github.com/web-infra-dev/rspack/assets/5899024/855e1dc1-ae9c-4713-976c-d067278ecd3d">

I have included a reproducible. It is based on https://github.com/module-federation/module-federation-examples/tree/master/advanced-api/dynamic-remotes, but with upgraded RSPack.

Note that with v0.7.0, HMR worked without problem.

### Reproduce link

https://github.com/markmssd/module-federation-runtime-shared/tree/rspack-0.7.1

### Reproduce Steps

```
git clone https://github.com/markmssd/module-federation-runtime-shared/tree/rspack-0.7.1
cd  module-federation-runtime-shared
pnpm install
pnpm start

// everything works so far.
// edit any file, e.g. `app1/src/App.js`, to trigger HMR
// it crashes 💥
```

**Comment by markmssd** [comment] 2024-06-05 17:58
Digging a bit more, I'm seeing https://github.com/web-infra-dev/rspack/pull/6670 and https://github.com/web-infra-dev/rspack/pull/6694 that _**might**_ be related, since they're touching the `module graph` as reported by the error, @jerrykingxyz would you know why this could happen? 🙏🏼

**Comment by jerrykingxyz** [comment] 2024-06-06 02:03
fixed by https://github.com/web-infra-dev/rspack/pull/6730

**Comment by markmssd** [comment] 2024-06-06 14:04
Ok so seems that using
```
      new rspack.container.ModuleFederationPlugin({
        name: 'core',
        shared,
      }),
```

is what makes it fail, however using 
```
      new rspack.container.ModuleFederationPluginV1({
        name: 'core',
        shared,
      }),
```

works without issue! Still weird that I can't reproduce it in https://github.com/markmssd/module-federation-runtime-shared/tree/rspack-0.7.1 though, I'll keep trying, but let me know if you have an idea of what could be wrong 🙏🏼

**Comment by opsidao** [comment] 2024-06-07 07:18
FWIW I'm seeing the same issue with:

```json
{
  "dependencies": {
    "@module-federation/enhanced": "^0.1.18",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@rsbuild/core": "^0.7.3",
    "@rsbuild/plugin-react": "^0.7.3",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "typescript": "^5.4.2"
  }
}

**Comment by ahabhgk** [comment] 2024-06-07 08:08
About the module federation issue, we need a reproduce here, or if you really can't reproduce you can provide the config file, I will try to reproduce based on the config file once my time available

**Comment by opsidao** [comment] 2024-06-07 09:06
@ahabhgk would something like [this](https://github.com/opsidao/rspack-issues-6740-repro) work?

**Comment by ahabhgk** [comment] 2024-06-07 09:08
The panic should already been fixed, try the latest nightly version

**Comment by opsidao** [comment] 2024-06-07 09:15
Confirmed, the panic is fixed in the nightly, thanks @ahabhgk !

**Comment by markmssd** [comment] 2024-06-08 00:23
@ahabhgk I was finally able to reproduce the issue, there you go: https://github.com/markmssd/module-federation-runtime-shared/tree/rspack-0.7.2-canary.

It's a problem only with dynamic imports. In this repro, it would be `app1/src/DynamicPage.js`. Editing this file will result in this error:

<img width="1668" alt="Screenshot 2024-06-07 at 8 20 03 PM" src="https://github.com/web-infra-dev/rspack/assets/5899024/2f3ae183-0433-45a9-a582-f53158b79406">

If you edit any other page, for example `app1/src/App.js`, it does not happen. I've also noticed that commenting out `ModuleFederationPlugin` in `app1/rspack.config.js` would fix it (however we wouldn't have Module Federation anymore so it's not really a solution, but could help pinpoint the issue).

Let me know if you need more info, I'd be glad to help further.

**Comment by markmssd** [comment] 2024-06-11 12:15
Hey @ahabhgk , just checking whether you had an idea why that would happen, and if you were able to see the error on the reproducible.

Also, should I re-open a new issue for it since the initial issue is technically resolved already?

**Comment by ahabhgk** [comment] 2024-06-11 12:20
Let's move to the new issue https://github.com/web-infra-dev/rspack/issues/6773, I will take a look in the next one or two days

**Closed by ahabhgk** 2024-06-11 12:20 UTC
Labels: bug, need reproduction
