### ISSUE TITLE
using custom cacheGroups breaks reusing existing chunks

### ISSUE THREAD

**Issue by ERuseckas** [web-infra-dev/rspack#2991] opened 2023-05-02 12:52 UTC
### System Info

System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.35 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh

  Binaries:
    Node: 18.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm

  Browsers:
    Brave Browser: 112.1.50.121
    Chrome: 112.0.5615.137
    Edge: 112.0.1722.58
    Firefox: 112.0.2
    Safari: 16.4

### Details

Hello,

I've been trying out rspack in a big web application, which uses webpack right now.
More or less I managed to migrate it in a desired way. Build time went down 3 times, which made me very happy.
But... I have one issue:
whenever I start using custom `cacheGroups` inside `splitChunks`, then output explodes in size, because chunks aren't reused/shared.
`reuseExistingChunk` doesn't have any impact at all in this case.
Using same custom cache groups in webpack doesn't have such an issue.

Using only default cache groups works fine tho.

### Reproduce Steps

use custom cache groups in a large code base:
* few groups to split vendors
* few groups to split source code

**Comment by hyf0** [comment] 2023-05-03 09:17
I understand your issue. But could provide a reproduction using https://github.com/web-infra-dev/rspack-repro. It would make me easier to fix the bug and especially add a test for this issue.

**Comment by hyf0** [comment] 2023-05-03 11:08
`reuseExistingChunk` is not supported yet and I'm working on it(soon). But still, providing a reproduction using https://github.com/web-infra-dev/rspack-repro would make me easier to add a test for this feature.

**Comment by ERuseckas** [comment] 2023-05-03 13:40
@hyf0 here it is: https://github.com/ERuseckas/rspack-repro
you'll notice that `moment` is added into 3 chunks, I'd expect it to be in a single chunk instead.

That's a very narrowed sample of my real cases :)

**Comment by hyf0** [comment] 2023-05-05 03:49
I just implement it at https://github.com/web-infra-dev/rspack/pull/3000.

You could try the newest nightly version at https://www.npmjs.com/package/@rspack/cli?activeTab=versions.

with enabling

```js
experiments: {
  newSplitChunks: true
},
```

**Comment by ERuseckas** [comment] 2023-05-08 06:26
@hyf0 it got a bit better, but still not perfect. I still have code, which is included into >1 chunk, but isn't supposed to. And it feels as if `priority` isn't taken into account correctly

**Comment by hyf0** [comment] 2023-05-08 06:34
> I still have code, which is included into >1 chunk

It might be expected because Rspack and Webpack would bundle duplicated code if the code is shared in multiple entries or dynamic entries.

You need to compare the output of Rspack and Webpack to check if the output of Rspack is the same as Webpack rather than whether have duplicated code.

If you just don't want to have duplicated code, you could just set `splitChunks.chunks = 'all'`.

**Comment by ERuseckas** [comment] 2023-05-09 07:22
@hyf0 some other day (right now too busy) I'll try to spend some more time on this to see if I can make a better sample for you to look into

Right now if I use identical cache groups in webpack and rspack, rspack makes way less chunks. And main biggest chunk in webpack is 9.6MB and in rspack it's 30.5MB, which is way too big a difference. Here is my result (left side is rspack):
<img width="1781" alt="image" src="https://user-images.githubusercontent.com/62941956/237023035-3a575649-7884-449f-85ba-5aede4254ab2.png">

p.s. I noticed that tree shaking in rspack works better. Good job 👍

**Comment by hyf0** [comment] 2023-05-10 10:24
> Right now if I use identical cache groups in webpack and rspack

Did you mean the identical cache groups in https://github.com/ERuseckas/rspack-repro/blob/main/config.mjs?

If so, I will look into https://github.com/ERuseckas/rspack-repro.

**Comment by ERuseckas** [comment] 2023-05-16 13:22
@hyf0 yes, in the linked repository you will find one case.

Another one I figured out recently is that it doesn't put into separate chunks dynamically imported 3rd party libraries, even tho it does put into separate chunks dynamically imported code. In both cases `@loadable/component` is used to do dynamic imports.

**Comment by hyf0** [comment] 2023-08-10 10:13
Please verify that is your issue solved in the currernt `nightly` version of Rspack.

**Comment by ERuseckas** [comment] 2023-08-10 10:18
@hyf0 my original issue is solved.
I just didn't check dynamically imported 3rd party libraries, because I made a workaround for it by placing those into their own chunks manually in config.

**Comment by hardfist** [comment] 2023-08-10 13:12
close this issue, @ERuseckas feel free to reopen if you still met problems

**Closed by hardfist** 2023-08-10 13:12 UTC
Labels: feat, p3-minor-bug
