### ISSUE TITLE
add sourcemap file to chunk.auxiliaryFiles

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rspack#3253] opened 2023-05-22 10:10 UTC
### What problem does this feature solve?

When I use rspack-manifest-plugin. I find that the sourcemap file is missing in manifest, then I found that it gets sourcemap file from chunk.auxiliaryFiles. But In rspack, it doesn't output sourcemap file to chunk.auxiliaryFiles.

<img width="716" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/3b0ffa15-6589-475b-baf5-87b155ec7c90">

The behavior in webpack:

<img width="476" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22373761/c2f94777-6adf-41f2-82c9-603cf7fbe7f5">

### What does the proposed API of configuration look like?

the same with webpack.

**Comment by hardfist** [comment] 2023-09-16 13:13
bump

**Comment by Hamzakh777** [comment] 2023-09-16 14:26
Assign it to me @hardfist

**Comment by Hamzakh777** [comment] 2023-09-25 15:03
After some investigation, it seems that the cause of this issue:
- `rspack-manifest-plugin` gets applied twice https://github.com/hardfist/rspack-manifest-plugin/blob/master/src/index.ts#L73 which results in `emitCountMap` https://github.com/hardfist/rspack-manifest-plugin/blob/master/src/index.ts#L11 having count of 2 instead of 1.
- It's been called twice because `html-webpack-plugin` uses a child compiler, and when that child compiler runs, the `beforeRun` hook on the `rspack-manifest-plugin` gets called again.

**Comment by flyingalex** [comment] 2024-01-26 17:38
Hi, I am following this issue and want to fix it, 

I roughly feel it's the process_assets_stage_dev_tooling method issue in `rspack_plugin_devtool` crate, how I can run related tests after I change the logic? checked `rspack_plugin_devtool` seems no tests there

Any suggestion would be very appreciated, thx

**Comment by flyingalex** [comment] 2024-03-12 15:41
@9aoy seems already fixed by the core team, please double check

**Comment by 9aoy** [comment] 2024-03-20 03:39
> @9aoy seems already fixed by the core team, please double check

@hulin32 looks not working in rspack v0.5.8 😢

**Comment by hulin32** [comment] 2024-03-21 15:53
@9aoy hey,  if you are talking about `rspack-manifest-plugin`, then it works, you can see  sourcemapfile in manifest, but its not using chunk.auxiliaryFiles

**Closed** 2024-04-18 07:14 UTC
Labels: feat, good first issue, team
