### ISSUE TITLE
worker support

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#1320] opened 2022-12-01 12:33 UTC
```[tasklist]
### Worker
- [ ] https://github.com/web-infra-dev/rspack/issues/3552
- [ ] https://github.com/web-infra-dev/rspack/issues/3073
- [x] ImportScriptChunkLoading (https://github.com/web-infra-dev/rspack/pull/2839)
- [ ] https://github.com/web-infra-dev/rspack/issues/3074
- [ ] https://github.com/web-infra-dev/rspack/issues/3658
- [ ] https://github.com/web-infra-dev/rspack/pull/3702
- [ ] https://github.com/web-infra-dev/rspack/pull/3703
- [ ] https://github.com/web-infra-dev/rspack/pull/3711
- [ ] https://github.com/web-infra-dev/rspack/pull/3731
- [ ] https://github.com/web-infra-dev/rspack/issues/3680
- [ ] https://github.com/web-infra-dev/rspack/issues/3656
- [ ] https://github.com/web-infra-dev/rspack/issues/3686
```

**Comment by thecodrr** [comment] 2023-03-13 08:06
`worker-loader` is required for basically any kind of Web Workers support so I think this should be high on the priority list.

**Comment by beaucollins** [comment] 2023-03-13 21:08
`webpack` says not to use `web-loader` any more https://webpack.js.org/guides/web-workers/#syntax

We use the method describe in those docs but that is also broken with `rspack`.

**Comment by ahabhgk** [comment] 2023-03-14 00:48
Rspack currently not support web-worker or worker-loader, but we will work on supporting them later.

**Comment by thecodrr** [comment] 2023-03-14 05:01
@beaucollins that method doesn't work on Firefox because there's no ESM support for Web Workers yet. Bundling is the only reliable way to make web workers work across browsers.

**Comment by beaucollins** [comment] 2023-03-14 13:58
@thecodrr webpack replaced thé `import.meta.url` with a static string. Firefox handles it just fine.

**Comment by beaucollins** [comment] 2023-03-23 23:22
Looks like #2340 will solve this for us. I'll report back.

**Comment by towavephone** [comment] 2023-04-06 13:59
Look like https://github.com/web-infra-dev/rspack/pull/2340 can't resolve the web worker as the same with webpack 5:
Uncaught SyntaxError: Cannot use import statement outside a module
there always exists some extra file need to be imported except set the worker.js to type: module?

**Comment by birtles** [comment] 2023-04-18 01:39
> I can confirm that we can successfully use our worker code using `rspack` and the `new URL('Module.ts', import.meta.url)` syntax.

I'm not sure what I'm doing differently.

With the following code using rspack 0.1.7, I get the TS file simply copied, _untransformed_ (but renamed), to the output directory:

```ts
const dbWorker = new Worker(
  /* webpackChunkName: 'db-worker' */
  new URL('../db-worker/db-worker.ts', import.meta.url)
);
```

**Comment by beaucollins** [comment] 2023-04-18 02:44
@birtles it seems I spoke too soon. The builds work but the Worker based feature is not.

**Comment by felixmosh** [comment] 2023-04-18 08:31
I've the same issue as @birtles has, I would expect that a new entry will be added (with the path of the `worker` file path) dynamically  with a worker target, so if the `worker` file path has `import`s it will be bundled together as it works in Webpack.

**Comment by pushkargupta9807** [comment] 2023-05-22 18:05
a gentle follow-up, do we have an approx ETA for this fix?

**Comment by pushkargupta9807** [comment] 2023-05-31 19:09
Do we have a patch/ experimental branch for this fix I can try ?

**Comment by hardfist** [comment] 2023-06-02 12:03
> Do we have a patch/ experimental branch for this fix I can try ?

it is not supported now, we will support it soon

**Comment by ssddi456** [comment] 2023-06-26 08:06
so if there is a milestone? this is a important feature for many complex system

**Comment by ahabhgk** [comment] 2023-06-26 12:20
I'm working on it, will support it in the next one or two weeks

**Comment by felixmosh** [comment] 2023-07-04 10:31
@ahabhgk I've tested `v0.2.5` with the worker, looks like it splits the worker script into a separate file, but it is not bundling it's imports inside this bundle.

```js
// some code
highlightWorker = new Worker(
        new URL('./worker.ts', import.meta.url)
);
```

```js
// worker.ts
import config from './config'; // this is not bundled inside the chunk that was created for worker.ts

console.log(config)
```

**Comment by ahabhgk** [comment] 2023-07-04 13:13
@felixmosh Is there any runtime error? Could you provide a reproduction so I can dig into this

**Comment by felixmosh** [comment] 2023-07-05 11:44
@ahabhgk this is weird, with the rspack starter, it works properly.

**Comment by zackarychapple** [comment] 2023-07-05 11:57
Love seeing worker support landing.

**Comment by ahabhgk** [comment] 2023-07-06 03:24
@felixmosh Could you try [0.2.5-canary-7886e38-20230706011015](https://www.npmjs.com/package/@rspack/core/v/0.2.5-canary-7886e38-20230706011015), I believe it have been fixed by #3703

**Comment by ahabhgk** [comment] 2023-07-11 09:10
We have completed the basic support for web worker in [v0.2.6](https://www.npmjs.com/package/@rspack/cli/v/0.2.6), enough to cover most common cases, you can checkout our [document for more detail](https://www.rspack.dev/guide/web-workers.html)

But there are some uncommon cases we still not able to cover for now:
  - #3686: not support create worker by function call syntax `navigator.serviceWorker.register()`
  - #3656: not support customize worker syntax by `module.parser.javascript.worker`
  - #3680: not support webpackEntryOptions magic comments `/* webpackEntryOptions: { filename: "workers/[name].js" } */`

Since these issue are blocked by the implementation of compile time evaluation and parser hooks in Rspack, so I decide to close this one and tracking these in their own issue, if you have any problem when using worker with Rspack, feel free to open a new issue and ping me.

**Closed by ahabhgk** 2023-07-11 09:10 UTC
Labels: tracking issue, team, p1-important
