### ISSUE TITLE
[Bug]: An error occurred when removing class in Vue `<style />`. Rerunning `npm run dev` resolved

### ISSUE THREAD

**Issue by wangzexi** [web-infra-dev/rspack#8208] opened 2024-10-24 03:52 UTC
### System Info

  System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 92.14 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.volta/tools/image/node/20.18.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.8.2 - ~/.volta/tools/image/node/20.18.0/bin/npm
    bun: 1.1.20 - ~/.bun/bin/bun
  Browsers:
    Chrome: 130.0.6723.59
    Safari: 17.6

### Details

Reproduce Steps

### Reproduce Steps

Reproduce Steps

```sh
npm create rsbuild@latest # Vue/TypeScript

npm run dev
```

https://github.com/user-attachments/assets/67f936f3-45d1-47ce-9a8a-14703efa4391

**Comment by CPunisher** [comment] 2024-11-10 08:32
duplicate of https://github.com/web-infra-dev/rspack/issues/7805

**Closed** 2024-12-07 04:49 UTC
Labels: bug
