### ISSUE TITLE
[Bug]: panic "Failed to send process dependencies result" in compiler/compilation

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#5574] opened 2024-02-02 04:50 UTC
### Details

https://github.com/web-infra-dev/rspack/blob/b4a98eef5d7d27635e87daca48a6fca0da2789c7/crates/rspack_core/src/compiler/compilation.rs#L756-L761

```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  Failed to send process dependencies result: SendError { .. }
Location: /Users/bytedance/github/rspack/crates/rspack_core/src/compiler/compilation.rs:761
```

### Reproduce Steps

webpack-test/configCases/errors/import-missing

**Comment by h-a-n-a** [comment] 2024-02-02 06:42
@JSerFeng 
I was wondering if this is caused by the exposed queue handlers which might break the contract that receiver should not be dropped until all queued tasks are finished.
We might have to take a look at your convenience.

**Comment by h-a-n-a** [comment] 2024-02-06 05:54
Fixed in https://github.com/web-infra-dev/rspack/pull/5610. As currently there's no way to test this, so I'll leave this issue open.

**Closed** 2024-03-06 07:56 UTC
Labels: bug, team
