### ISSUE TITLE
开启 module federation 后 在低版本浏览器下报错！

### ISSUE THREAD

**Issue by ckken** [web-infra-dev/rspack#5969] opened 2024-03-19 08:43 UTC
>https://github.com/web-infra-dev/rspack/blob/873cfadd3487c84966daa8d23b10ad49473f04f8/crates/rspack_plugin_mf/src/sharing/consumesCommon.js#L110

+ 开启 mf 为 1.0
+ uagent Mozilla/5.0 (Linux; U; Android 7.1.1; zh-cn; MI 6 Build/NMF26X) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.146 Mobile Safari/537.36 XiaoMi/MiuiBrowser/9.2.11
+ 报错 ​ Uncaught SyntaxError: Invalid regular expression: /(?<=[-0-9A-Za-z])\s+/: Invalid group

**Comment by ahabhgk** [comment] 2024-03-21 06:59
Since you already find the cause, would you want to send a PR?

**Comment by ckken** [comment] 2024-03-22 03:57
我等下 PR下 本地环境自动格式化 怕 影响你们代码格式 试试线上 fork pr

**Comment by ckken** [comment] 2024-03-22 05:10
https://github.com/web-infra-dev/rspack/pull/6002 解决 module federation 1.0 正则
目前 1.5 也有兼容性问题 还在定位

**Comment by ckken** [comment] 2024-03-22 05:28
![image](https://github.com/web-infra-dev/rspack/assets/3890513/1778a946-d5f9-40d0-9aac-77dd875a6c38)
1.5 的问题大概率是 mf runtime 没走编译直接输出 导致一系列兼容性问题 希望可以根据系统进行兼容性编译

**Comment by wzc321** [comment] 2024-05-16 00:53
确实是的，没走编译，导致里面大量let、箭头函数

**Comment by chenjiahan** [comment] 2024-05-17 05:25
Related issue in Rsbuild: https://github.com/web-infra-dev/rsbuild/issues/2360 (will be fixed in the next version)

For Rspack users, you can add the following Rspack rule to match the virtual modules created by the ModuleFederationPlugin:

```js
// rspack.config.js
module.exports = {
  module: {
    rules: [
      {
        mimetype: {
          or: [
            'text/javascript',
            'application/node',
            'application/javascript'
          ]
        },
        use: [
          {
            loader: 'builtin:swc-loader',
            options: {
              // some SWC options
            }
          }
        ],
      },
    ]
  },
}
```

**Comment by 2heal1** [comment] 2024-05-20 02:32
for rspack, you can add below configuration to downgrade `@module-federation/runtime` : 

```js
// rspack.config.js
  module: {
    rules:[
      {
        mimetype: {
          or: [
            'text/javascript',
            'application/node',
            'application/javascript'
          ]
        },
        use: {
          loader: 'builtin:swc-loader',
          options: {
            env: {
              targets: [
                "> 0.5%",
                "not dead",
                "IE 11"
              ],
            },
            jsc: {
              parser: {
                syntax: 'ecmascript',
                jsx: true,
              },
              transform: {
                react: {
                  pragma: 'React.createElement',
                  pragmaFrag: 'React.Fragment',
                  throwIfNamespace: true,
                  development: false,
                  useBuiltins: false,
                },
              },
          
            },
          },
        },
        type: 'javascript/auto',
      },
      {
        test: /\.jsx?$/,
        use: {
          loader: 'builtin:swc-loader',
          options: {
            env: {
              targets: [
                "> 0.5%",
                "not dead",
                "IE 11"
              ],
            },
            jsc: {
              parser: {
                syntax: 'ecmascript',
                jsx: true,
              },
              transform: {
                react: {
                  pragma: 'React.createElement',
                  pragmaFrag: 'React.Fragment',
                  throwIfNamespace: true,
                  development: false,
                  useBuiltins: false,
                },
              },
          
            
            },
          },
        },
        type: 'javascript/auto',
      },
    ]
  },
```

I recommend you use rsbuild , it will auto apply you targets , no need to config so complex. And the `rsbuild@0.7.0` will be release this week

**Comment by wzc321** [comment] 2024-05-20 02:42
Thanks, I prefer to use Rsbuild  and I will wait for the next version.

**Closed** 2024-05-30 07:57 UTC
Labels: bug
