### ISSUE TITLE
[Bug Report]: Externals exclusion only works on direct matches 

### ISSUE THREAD

**Issue by ScriptedAlchemy** [web-infra-dev/rspack#2382] opened 2023-03-21 00:46 UTC
### System Info

  System:
    OS: macOS 13.2.1
    CPU: (20) x64 Apple M1 Ultra
    Memory: 354.18 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.2/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
  Browsers:
    Brave Browser: 107.1.45.118
    Chrome: 111.0.5563.64
    Safari: 16.3
  npmPackages:
    @rspack/cli: ^0.1.1 => 0.1.1 
    @rspack/core: ^0.1.1 => 0.1.1 

### Details

I am using rspack to compile my lambda handlers / custom server that sits ontop of next.js 

As such i want to exclude next.js from being bundled. 

This works if i set externals to `next: next` and `require('next')` 

however, rspack does not externalize something like this:
`const NextServer = require("next/dist/server/next-server").default;`

I can workaround the issue to some extent with:

```js
const NextServer = __non_webpack_require__("next/dist/server/next-server").default;
const nextConfig = __non_webpack_require__("../../next.config");
const serverConfig = Object.assign({}, defaultConfig, nextConfig);
```

Reasoning: 
Externals should allow regex matching expressions like /next/ or /next/$ as well as externals should exclude a string that startsWith a string. 

If i make react an external, in webpack we do not need to also include react/jsx-runtime or any other possible files that could be required. 

### Reproduce link

https://github.com/ScriptedAlchemy/next-rspack-custom-server

### Reproduce Steps

1. yarn install
2. yarn build-server

Look in server.js, currently this server is not hooked up to dev command, so i am purely testing if i can get dist/server.js to emit successfully before i attempt to leverage a bundled server file.

**Comment by hardfist** [comment] 2023-03-21 05:31
@ScriptedAlchemy try this version @rspack/cli@0.0.0-canary-d95be9e

**Comment by ScriptedAlchemy** [comment] 2023-03-21 07:34
@hardfist I'll test tomorrow morning. Thank you for such fast resolution!

**Comment by ScriptedAlchemy** [comment] 2023-03-21 20:11
@hardfist, there is still some over explicit condition matches.

```js
  externals: [
    /next\/dist/,
    /@swc/,
    /@vercel/,
    /@next/,
    /uglify-js/,
    /esbuild/,
    {
     '../next.config.js': 'next.config.js', // doesn't work
      '../next.config': 'next.config.js', //works
    }
  ]
```

it looks like rspack interparates string extenrals literally, so if i require without .js on the end, it will attempt to bundle it.

We might want to allow for matching without extension when using string. 

If i use regex to exclude file, that now works!

but i can get parse errors with 

`/next.config/`

which returns error: 
```
error[javascript]: JavaScript parsing error
   ┌─ main.js:48:18
   │
48 │ module.exports = ../next.config.js},
   │                  ^ Expression expected

```

**Comment by hardfist** [comment] 2023-03-22 14:10
i check the behavior of webpack and it seems it doesn't work for webpack neither
```
  externals: [
    {
     '../next.config.js': 'next.config.js', // doesn't work
      '../next.config': 'next.config.js', //works
    }
  ]
```
I think this is by design otherwise we need to wait for resolve result to decide whether the module need to be external which may cause resolve failure.

**Comment by ScriptedAlchemy** [comment] 2023-03-22 17:55
yeah this is something ive encountered before with webpack too, but hard to know exactly why. I think its because the package.json in next doesn't have a `type` so it doesn't know how to resolve or if its supposed to? 

I usually use the function for resolving externals, when i need to handle various module formats. 

Whats strange too is if i put `commonjs ../next.config.js` it will just emit that string as well. 

A dirty workaround ive used in webpack in for rspack was to make the external be `require('../next.config')` so it just passes through the string.

If webpack behaves the same way, then i dont think its a bug :)

**Comment by hardfist** [comment] 2023-03-26 10:14
`commonjs ../next.config.js` should be supported in 0.0.0-canary-b6ab7b7 please check

**Comment by hardfist** [comment] 2023-04-12 01:38
@ScriptedAlchemy is this issue solved now?

**Comment by hardfist** [comment] 2023-04-17 05:43
closed it now, feel free to open another if you find it now solve your problem.

**Closed by hardfist** 2023-04-17 05:43 UTC
Labels: bug
