### ISSUE TITLE
Rspack hmr break when use multiple compiler

### ISSUE THREAD

**Issue by shaodahong** [web-infra-dev/rspack#4183] opened 2023-09-13 02:38 UTC
### System Info

System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 AMD EPYC 7763 64-Core Processor
    Memory: 5.45 GB / 7.75 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.6.0 - ~/nvm/current/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.8.1 - ~/nvm/current/bin/npm
    pnpm: 8.7.1 - ~/nvm/current/bin/pnpm
  npmPackages:
    @rspack/cli: latest => 0.3.2

### Details

i have multiple entry `first` and `last`, and when I change some console log text, first entry break when hot update, and when I change to webpack, is fine.

<img width="726" alt="image" src="https://github.com/web-infra-dev/rspack/assets/14831261/b2506a4b-69cf-4b1e-9e23-f206513e8067">

### Reproduce link

https://github.com/shaodahong/rspack-repro-runtime

### Reproduce Steps

1. pn i
2. node build.mjs

and can switch `isRunningWebpack` test webpack or rspack

**Comment by ahabhgk** [comment] 2023-09-18 04:59
I notice that you change the `client.webSocketURL` to a remote address, reproduce failed because of that, and then I remove it, make sure all the request is sending to local, and add html, define configuration, then I successfully open the page, but hmr works properly, I can't reproduce the problem on my local env

Since you change the hmr request to a remote address, the problem might caused by that, can you make sure the hot update chunk file is emitted to the remote address?
<img width="715" alt="Screenshot 2023-09-18 at 12 53 46" src="https://github.com/web-infra-dev/rspack/assets/42857895/b927709c-1272-4c54-8eff-e33e4e37afdc">

If you sure it's a bug on rspack, please provide a reproduction that I can reproduce on the local env

**Comment by shaodahong** [comment] 2023-09-18 05:58
> I notice that you change the `client.webSocketURL` to a remote address, reproduce failed because of that, and then I remove it, make sure all the request is sending to local, and add html, define configuration, then I successfully open the page, but hmr works properly, I can't reproduce the problem on my local env
> 
> Since you change the hmr request to a remote address, the problem might caused by that, can you make sure the hot update chunk file is emitted to the remote address? <img alt="Screenshot 2023-09-18 at 12 53 46" width="715" src="https://user-images.githubusercontent.com/42857895/268558018-b927709c-1272-4c54-8eff-e33e4e37afdc.png">
> 
> If you sure it's a bug on rspack, please provide a reproduction that I can reproduce on the local env

@ahabhgk In my repro, i use `Codespaces` so i set remote socket, and in the evening, I will change the example to the local one.

**Comment by shaodahong** [comment] 2023-09-18 13:28
> If you sure it's a bug on rspack, please provide a reproduction that I can reproduce on the local env

I have updated my repository and remove remote socket url, but the problem still exists. and steps

1. `pnpm install`
2. `node build.mjs`
3. open `http://127.0.0.1:8081/`, and you can view the logs in the console.
4. change `src/last/index.js` log text, it is good
5. change `src/first/index.js` log text, broken
<img width="653" alt="image" src="https://github.com/web-infra-dev/rspack/assets/14831261/43d6a29e-45db-4238-8c4d-e9b297068849">

**Comment by ahabhgk** [comment] 2023-09-20 10:59
Thanks for your report! This will be fixed in next release

**Closed** 2023-09-21 05:36 UTC
Labels: bug, awaiting more feedback
