### ISSUE TITLE
[Feature Request]: Benchmark vs esbuild, turbopack, etc.

### ISSUE THREAD

**Issue by strager** [web-infra-dev/rspack#2155] opened 2023-03-10 20:06 UTC
### What problem does this feature solve?

I want to evaluate Rspack and compare it to the tool I currently use: esbuild.

### What does the proposed API of configuration look like?

1. column on the benchmark page with esbuild data (for both "all" and "react-components-10000"): https://www.rspack.dev/misc/benchmark.html
2. bar on the home page (under "Blazing Fast Build Speed") with esbuild data: https://www.rspack.dev/

**Comment by hardfist** [comment] 2023-03-10 23:48
we don't want to compare against bundlers other than webpack, because they may have different focus, for example since esbuild doesn't support JS HMR, it's not fair to compare HMR with esbuild, but you are free to fork our benchmark repo to test against esbuild yourself.

**Comment by hardfist** [comment] 2023-03-17 12:07
closes as this is by design

**Comment by jpike88** [comment] 2023-04-13 04:05
that's not really a good enough reason to me. so what if they don't have perfect feature parity? benchmarks are designed to be specific. as a person comparing the two, this just made me want to use esbuild instead.

**Comment by hardfist** [comment] 2023-04-19 09:33
@strager @jpike88 sorry about the miscommunication before, we're going to add benchmark about vite | esbuild | rollup | turbopack,  can you help tell which benchmark data you care about most, so we can add it.

**Comment by Boshen** [comment] 2023-04-19 09:43
"by design" is pretty soft in Chinese but sounds a bit harsh in English. The intention was to not start the benchmark game from us, but apparently the game has been started [from other parties](https://gist.github.com/sapphi-red/db27f9c18ed31894e409224051119e1b). We'll start adding the benchmarks. Apologies for the miscommunication.

**Comment by hyf0** [comment] 2023-05-11 07:13
Sync up by Rspack team:

We will create a benchmark repo like https://github.com/sapphi-red/performance-compare/tree/main and add esbuild in it.

**Comment by IWANABETHATGUY** [comment] 2023-05-24 08:18
We have been updated esbuild benchmark comparison,  https://github.com/web-infra-dev/performance-compare/tree/fix/esbuild,

**Comment by IWANABETHATGUY** [comment] 2023-05-24 13:18
Closed in favor of https://github.com/web-infra-dev/performance-compare/pull/1

**Closed by IWANABETHATGUY** 2023-05-24 13:18 UTC
Labels: feat

**Comment by tomByrer** [comment] 2024-02-12 12:42
> evaluate Rspack

https://github.com/farm-fe/performance-compare?tab=readme-ov-file#performance-compare
