### ISSUE TITLE
[Bug]: Order in entrypoints array not respected with chunks

### ISSUE THREAD

**Issue by CPatchane** [web-infra-dev/rspack#6696] opened 2024-05-30 15:06 UTC
### Version

```sh
System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 85.20 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Browsers:
    Brave Browser: 120.1.61.116
    Chrome Canary: 127.0.6510.0
    Safari: 16.6
  npmPackages:
    @rsbuild/core: ^0.7.1 => 0.7.1
    @rsbuild/plugin-sass: ^0.7.1 => 0.7.1
```

### Details

I have two files that I want to bundle, things work well when everything is bundled in one file but the order is not the correct one when things are chunked.

rsbuild.config.ts
```
  source: {
    entry: {
      index: "./src/index.ts",
      styleEntry: [
        "./src/style.scss",
        "./node_modules/@drivy/cobalt/utilities.css",
      ]
    },
  },
```

After the build I get
```
"styleEntry": [
      "static/css/cobalt-utilities.b4d0fa8d.css",
      "static/css/styleEntry.752d740e.css",
      "static/js/styleEntry.ba612797.js"
    ]
```

Got: `cobalt-utilities` loaded before my main entry `style.scss`
Expected: Load `style.scss` before the chunk `cobalt-utilities`

### Reproduce link

https://github.com/CPatchane/rsbuild-sass-issue

### Reproduce Steps

1- `pnpm build`
2- See order in manifest.json
or
1- `pnpm dev`
2- see order in the `<head>` on [the styleEntry page](http://localhost:3000/styleEntry)

**Comment by chenjiahan** [comment] 2024-05-31 08:06
I have transferred this issue to the Rspack repo as it may be relevant to Rspack split chunks.

**Comment by CPunisher** [comment] 2024-06-11 03:37
I tried webpack with the same result.
My guess is that the module graph is missing the ordering information specified in the configuration, and therefore doesn't represent the order correctly when splitting the chunk (perhaps this meets expectation).

If you specify multiple entries in rspack, the order is preserved and packaged into different chunks, but in rsbuild each entry is generated as a separate html.

So I found a dirty way to package the styleEntry separately with `tool.rspack`:
```js
import { defineConfig } from "@rsbuild/core";
import rspack from "@rspack/core";

export default defineConfig({
  source: {
    entry: {
      styleEntry: [
        "./src/style.css",
        "./node_modules/@drivy/cobalt/utilities.css",
      ],
    },
  },
  tools: {
    rspack: {
      entry: {
        a: "./src/style.css",
        b: "./node_modules/@drivy/cobalt/utilities.css",
      },
      plugins: [
        new rspack.HtmlRspackPlugin({
          // Specify the chunks, or everything will be injected in this html.
          chunks: ["a", "b"],
        }),
      ],
    },
  },
});
```

**Comment by hardfist** [comment] 2024-08-10 11:16
it seems not a bug of rspack and maybe related to https://github.com/orgs/web-infra-dev/discussions/12

**Closed** 2024-08-10 11:17 UTC
Labels: same as webpack
