### ISSUE TITLE
Panic in require.context regex

### ISSUE THREAD

**Issue by glenjamin** [web-infra-dev/rspack#4557] opened 2023-11-07 13:39 UTC
### System Info

  System:
    OS: macOS 12.7
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 404.37 MB / 32.00 GB
    Shell: 5.1.8 - /usr/local/bin/bash
  Binaries:
    Node: 18.8.0 - ~/.asdf/installs/nodejs/18.8.0/bin/node
    npm: 8.18.0 - ~/.asdf/installs/nodejs/18.8.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.105
    Edge: 119.0.2151.46
    Firefox: 119.0
    Safari: 17.0
  npmPackages:
    @rspack/cli: ^0.3.11 => 0.3.11

### Details

The following line in my code
```
const context = require.context('../src', true, /-story\.js$/);
```
causes this panic
```
> RUST_BACKTRACE=full npx -- rspack build
thread 'tokio-runtime-worker' panicked at crates/rspack_regex/src/algo.rs:110:31:
internal error: entered unreachable code
stack backtrace:
   0:        0x11751be7b - _napi_register_module_v1
   1:        0x117540d73 - _napi_register_module_v1
   2:        0x11751891e - _napi_register_module_v1
   3:        0x11751bc59 - _napi_register_module_v1
   4:        0x11751cfa5 - _napi_register_module_v1
   5:        0x11751cd24 - _napi_register_module_v1
   6:        0x11751d403 - _napi_register_module_v1
   7:        0x11751d2ec - _napi_register_module_v1
   8:        0x11751c359 - _napi_register_module_v1
   9:        0x11751d072 - _napi_register_module_v1
  10:        0x1176da0d5 - _napi_register_module_v1
  11:        0x1176da167 - _napi_register_module_v1
  12:        0x116897596 - <unknown>
  13:        0x116651095 - <unknown>
  14:        0x116594fed - <unknown>
  15:        0x1163ca77c - <unknown>
  16:        0x11642522c - <unknown>
  17:        0x1163ca77c - <unknown>
  18:        0x11642fd3c - <unknown>
  19:        0x116596ae7 - <unknown>
  20:        0x11657ad22 - <unknown>
  21:        0x1166dd6ea - <unknown>
  22:        0x1166f7534 - <unknown>
  23:        0x1166f3290 - <unknown>
  24:        0x11590e6e6 - <unknown>
  25:        0x115829a95 - <unknown>
  26:        0x11584afaa - <unknown>
  27:        0x1159082e6 - <unknown>
  28:        0x1174e58d8 - _napi_register_module_v1
  29:        0x1174e4145 - _napi_register_module_v1
  30:        0x1174e8bc0 - _napi_register_module_v1
  31:        0x1174d9f87 - _napi_register_module_v1
  32:        0x1174db15d - _napi_register_module_v1
  33:        0x117522469 - _napi_register_module_v1
  34:     0x7ff8089174e1 - __pthread_start
[rspack-cli] [Error: error[internal]: internal error: entered unreachable code
This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.
   0: _napi_register_module_v1
   1: _napi_register_module_v1
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: _napi_register_module_v1
   7: _napi_register_module_v1
   8: _napi_register_module_v1
   9: _napi_register_module_v1
  10: _napi_register_module_v1
  11: _napi_register_module_v1
  12: __pthread_start


] {
  code: 'GenericFailure'
}
```

If the regex is changed to the following, then there is no longer a panic
```
const context = require.context('../src', true, /-story\.js/);
```

So I presume this is an error in the regex compilation.

**Comment by hverlin** [comment] 2023-11-07 23:26
Hit the same issue. Seems that a workaround is to add a flag like `g` if possible to your regex and then it will use the slow path?

https://github.com/web-infra-dev/rspack/blob/83b75945aec039fceed47b8cf70b71545c6cc1a1/crates/rspack_regex/src/algo.rs#L61-L71

**Comment by bvanjoi** [comment] 2023-11-08 03:02
This issue can be effortlessly resolved by changing the code from ﻿`unreachable` to `﻿false` in both the [global](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_regex/src/algo.rs#L100) and [sticky](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_regex/src/algo.rs#L107), as there seem to be logical errors present.

**Comment by hardfist** [comment] 2023-11-08 03:10
> Hit the same issue. Seems that a workaround is to add a flag like `g` if possible to your regex and then it will use the slow path?
> 
> https://github.com/web-infra-dev/rspack/blob/83b75945aec039fceed47b8cf70b71545c6cc1a1/crates/rspack_regex/src/algo.rs#L61-L71

@hverlin since you already spot the problem code, are you interested in fixing it for us, we can help guide if you meet any problems

**Comment by hverlin** [comment] 2023-11-08 18:37
Managed to reproduce when building from source.
The issue is that I don't know exactly what's triggering it. In the debug build, I just get
```
[1]    349798 segmentation fault (core dumped)
```

when I add some trace log and run with `RSPACK_PROFILE=TRACE=layer=logger&filter=info` I only get
```
INFO rspack_regex::algo: EndWith { pats: ["-page-object"] }
    at crates/rspack_regex/src/algo.rs:113
```

Will try to set up what's suggested on this page: https://web-infra-dev.github.io/rspack-dev-guide/debugging/intro.html

**Comment by hverlin** [comment] 2023-11-08 21:50
https://github.com/web-infra-dev/rspack/blob/dd28d7a76f18b2d4b829af9c18766886c5db67c3/crates/rspack_core/src/context_module.rs#L84-L90

Unless the `algo` is made public, there is no way for the caller to know if they can call `global` or `sticky` so it makes sense to return `false`. Also, technically, the regexes supported by the `endWith` algo don't have flags.

Will create a PR

**Closed** 2023-11-09 03:13 UTC
Labels: bug, good first issue, contrib: easy
