### ISSUE TITLE
[Bug]: *.LICENSE.txt can vary between every build, and it's leaking sensitive information about the environment

### ISSUE THREAD

**Issue by ambar** [web-infra-dev/rspack#5907] opened 2024-03-09 13:25 UTC
### System Info

  System:
    OS: macOS 11.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
    Memory: 81.54 MB / 24.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.1 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome Canary: 124.0.6347.0
    Edge: 122.0.2365.80
    Safari Technology Preview: 15.4

## Hundreds or thousands of lines of changes, a huge git diff

it should be sorted by the names:

![image](https://github.com/web-infra-dev/rspack/assets/105919/b859206f-496c-43b7-8c17-f383d43cf3bf)

## Privacy information leakage

the working directory should be stripped from the file path:

![image](https://github.com/web-infra-dev/rspack/assets/105919/68a3ff82-e01b-40ea-96b8-f352b1bf7cc9)

### Reproduce Steps

`rspress build` any project, deploy to gh-pages.

**Comment by LingyuCoder** [comment] 2024-03-12 10:42
cc @10Derozan

**Comment by 10Derozan** [comment] 2024-03-13 06:11
OK,I will check it

**Comment by 10Derozan** [comment] 2024-03-13 08:20
> cc @10Derozan

rspress / rsbuild only enable extractComments by default, maybe rspack should keep the comments stable.

**Comment by h-a-n-a** [comment] 2024-04-26 09:15
I cannot reproduce the relative case, would you please add a reproduction demo? The stability issue is fixed in the PR above.

**Comment by h-a-n-a** [comment] 2024-04-26 09:15
I would like to close this issue since it's been too long. Feel free to reopen this once you have demo ready.

**Closed** 2024-04-26 09:25 UTC
Labels: bug
