### ISSUE TITLE
[Bug]: Panic occurred at runtime. with v 0.5.6 on Windows

### ISSUE THREAD

**Issue by pushkargupta9807** [web-infra-dev/rspack#5897] opened 2024-03-08 01:31 UTC
### System Info

  System:
    OS: Windows 10 10.0.22631
    CPU: (40) x64 Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
    Memory: 43.98 GB / 63.66 GB
  Binaries:
    Node: 20.11.1 - ~\.nvm\versions\node\v20.11.1\bin\node.EXE
    Yarn: 1.23.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.2.4 - ~\.nvm\versions\node\v20.11.1\bin\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: 0.5.6 => 0.5.6
    @rspack/core: 0.5.6 => 0.5.6

### Details

It seems that the previously filed bug is not fixed with the latest oxc_resolver (https://github.com/web-infra-dev/rspack/issues/5592)
I am running into that issue on windows machine as below: 

Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  internal error: entered unreachable code: Path "D:\\source\\services-io-sharepoint-share" Subpath "/inde
x.ts"
Location: C:\Users\ContainerAdministrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\oxc_resolver-1.5.4\src\path.rs:74

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: napi_register_module_v1
    at <unknown source file>
●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (63%) building builtin:swc-loader??ruleSet[1].rules[13].use[0]!D:\source\reponame\packages\services\io\services-some-service\
2: napi_register_module_v1
    at <unknown source file>
 3: napi_register_module_v1
    at <unknown source file>
 4: napi_register_module_v1
    at <unknown source file>
 5: napi_register_module_v1
    at <unknown source file>
 6: napi_register_module_v1
    at <unknown source file>
 7: napi_register_module_v1
    at <unknown source file>
 8: napi_register_module_v1
    at <unknown source file>
 9: napi_register_module_v1
    at <unknown source file>
10: napi_register_module_v1
    at <unknown source file>
11: napi_register_module_v1
    at <unknown source file>
12: napi_register_module_v1
    at <unknown source file>
13: napi_register_module_v1
    at <unknown source file>
14: napi_register_module_v1
    at <unknown source file>
15: napi_register_module_v1
    at <unknown source file>
16: napi_register_module_v1
    at <unknown source file>
17: napi_register_module_v1
    at <unknown source file>
18: napi_register_module_v1
    at <unknown source file>
19: napi_register_module_v1
    at <unknown source file>
20: napi_register_module_v1
●  ━━━━━━━━━━━━━━━━━━━━━━━━━ (63%) building D:\source\node_modules\@metaos\hub-sdk\dist\Hosts\use-create-app-host-sdk.js
    at <unknown source file>
21: napi_register_module_v1
    at <unknown source file>
22: napi_register_module_v1
    at <unknown source file>
23: napi_register_module_v1
    at <unknown source file>
24: napi_register_module_v1
    at <unknown source file>
25: BaseThreadInitThunk
    at <unknown source file>
26: RtlUserThreadStart
    at <unknown source file>
Done in 57.89s. Peak memory usage 30.40MB.

### Reproduce Steps

Try starting an app (serve) with rspack v0.5.6

**Comment by pushkargupta9807** [comment] 2024-03-08 01:31
@Boshen @hardfist FYI

**Comment by Boshen** [comment] 2024-03-08 02:13
@pushkargupta9807 Can you post your rspack config (mainly the resolve part), there's probably something not handled with path aliases, it would be great if you can show me their values.

```
entered unreachable code: Path "D:\source\services-io-sharepoint-share" Subpath "/inde
x.ts"
```

I'm interested in where `"/index.ts"` is coming from.

**Comment by Tenodec** [comment] 2024-03-17 10:01
Please check if the project path contains Chinese characters，i got right work by change  to all english path

**Comment by Boshen** [comment] 2024-03-29 02:48
Closing due to lack of reproduction.

**Closed by Boshen** 2024-03-29 02:48 UTC
Labels: bug, awaiting more feedback

**Comment by kbzowski** [comment] 2024-07-09 11:05
I got the same error with yarn@4, setting `nodeLinker: node-modules` in .yarnrc.yml solved it.
