### ISSUE TITLE
[Bug Report]: `resolve.tsConfigPath` does nothing

### ISSUE THREAD

**Issue by GarrisonD** [web-infra-dev/rspack#2170] opened 2023-03-11 14:06 UTC
### System Info

```
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 618.58 MB / 1.63 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @rspack/cli: latest => 0.1.0
```

### Details

Specifying `resolve.tsConfigPath` has no effect: `compilerOptions.baseUrl` and `compilerOptions.paths` from `tsconfig.json` are ignored.

### Reproduce link

https://codesandbox.io/p/sandbox/new-leaf-qxbh8e

### Reproduce Steps

Run `npm run build:ts` to see that TS has no resolve issues.

Run `npm run build` and see:

```
error[internal]: Resolve error
  ┌─ src/App.tsx:3:1
  │
3 │ import Button from "components/Button";
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Failed to resolve components/Button in /project/home/garrisond/workspace/src/App.tsx
```

**Comment by GarrisonD** [comment] 2023-03-11 14:15
In the case of a simple setup like mine, this can be a **solution**:

```diff
- resolve: { tsConfigPath: "./tsconfig.json" },
+ resolve: { modules: ["node_modules", "src"] },
```

You can run `npm run build-modules` and see that it works like a charm.

**Comment by GarrisonD** [comment] 2023-03-16 13:30
@bvanjoi I updated the Code Sandbox to the latest of `rspack 0.1.1` but the issue still presents 😞

**Comment by GarrisonD** [comment] 2023-03-16 13:45
@bvanjoi I would be happy to help, just let me know how.

**Comment by bvanjoi** [comment] 2023-03-16 14:11
I found out the reason for this.

First, there was indeed a problem with resolving relative paths based on `baseUrl` in #2174 before, but #2174 fixes it.

The problem is now caused by the need to pass an absolute path to tsconfig.

Also, the current error reporting is misleading and I have added a new error to https://github.com/web-infra-dev/rspack/pull/2264/files#diff-e3cb84e19ccc823fb214fdbb9dcd1afe8de633c34762f11d11a2c22a1fff2238R77 to try and fix it.

So, you can change `'./tsconfig.json'` to `path.resolve(__dirname, './tsconfig.json')` to fix that

**Comment by GarrisonD** [comment] 2023-03-16 14:22
Can we expect one day `'./tsconfig.json'` to be a valid option?

For `entry: { main: "./src/index.tsx" }`, it works fine. That would be great to keep it consistent.

**Comment by GarrisonD** [comment] 2023-03-16 14:23
I can confirm that with `path.resolve(...)` it works! Thanks a lot for your assistance!

**Comment by bvanjoi** [comment] 2023-03-16 14:31
> Can we expect one day './tsconfig.json' to be a valid option?

track this in #2312

**Closed by bvanjoi** 2023-03-16 14:31 UTC
Labels: C-bug
