### ISSUE TITLE
loose module when cache and tree shake enabled

### ISSUE THREAD

**Issue by ahabhgk** [web-infra-dev/rspack#3465] opened 2023-06-07 11:18 UTC
### System Info

  System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 87.73 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/99949_1685947570497/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/99949_1685947570497/bin/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/99949_1685947570497/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Edge: 113.0.1774.57
    Safari: 16.3

### Details

https://github.com/web-infra-dev/rspack/blob/8fd46171460e4ae186d1fc80e63e6441a49ab83b/crates/rspack_core/src/tree_shaking/optimizer.rs#L1238

The `m.ast()` will return `None` when cache is enabled, this causes `include_module_ids` not include the module's dependency modules

https://github.com/web-infra-dev/rspack/blob/8fd46171460e4ae186d1fc80e63e6441a49ab83b/crates/rspack_plugin_javascript/src/runtime.rs#L30

### Reproduce link

https://codesandbox.io/p/sandbox/rspack-cache-tree-shake-bug-pxq75i

### Reproduce Steps

open codesandbox link and run `node ./run.js`

**Comment by hardfist** [comment] 2023-07-12 09:37
@ahabhgk  loose module or lose module?

**Comment by ahabhgk** [comment] 2023-07-12 09:42
loose

**Comment by IWANABETHATGUY** [comment] 2023-08-01 07:46
What is your expected behavior? console `ok` ?

**Comment by ahabhgk** [comment] 2023-08-01 08:18
Same output in `dist-old` and `dist`

**Comment by ahabhgk** [comment] 2023-08-01 08:51
The hash should be the same

**Comment by IWANABETHATGUY** [comment] 2023-08-01 09:12
then it looks like we can close this.

**Closed** 2023-08-01 09:34 UTC
Labels: bug, team, pending triage
