### ISSUE TITLE
`swc_visit::AstNodePath<N>::with` expanding to 227k LOC

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/rspack#3058] opened 2023-05-08 09:24 UTC
### System Info

None

### Details

https://github.com/web-infra-dev/rspack/blob/f27bb0d740165d32c52f0770e22e68914991ee98/crates/rspack_plugin_javascript/src/visitors/dependency/hmr_scanner.rs#L100-L137

Suggestions:

refactor the code so it doesn't expand to so much code

### Reproduce Steps

`cargo llvm-lines -p rspack_plugin_javascript | head -20`

```
  Lines                  Copies               Function name
  -----                  ------               -------------
  1062678                30828                (TOTAL)
   227944 (21.4%, 21.4%)  3562 (11.6%, 11.6%) swc_visit::AstNodePath<N>::with
```

**Comment by bvanjoi** [comment] 2023-05-09 07:03
huge count `.with()` is not caused by `visit_node_children` in `hmr_scanner.rs`

we can confirm it by comment that:

before:

<img width="1560" alt="image" src="https://user-images.githubusercontent.com/30187863/237019495-1930a589-d25a-4afa-a3fb-6a4f5eae5073.png">


after:

<img width="1560" alt="image" src="https://user-images.githubusercontent.com/30187863/237019609-fecf030b-b0c9-4c47-a886-cedea6792ad5.png">

**Comment by Boshen** [comment] 2023-05-09 09:23
Where is this coming from 🤔 ?

**Comment by Boshen** [comment] 2023-05-10 03:47
Apparently using `AstNodePath<AstParentNodeRef>` will generate the code for every single AST Node, there's not much we can do right now.

**Comment by Boshen** [comment] 2023-05-24 03:34
Oh I didn't know about `rustflags = ["-Z", "share-generics=yes"]`, let me give it a research and try.

**Comment by kdy1** [comment] 2023-05-24 05:35
https://github.com/swc-project/swc/pull/7442 will fix this

**Comment by underfin** [comment] 2023-06-29 09:02
closed by https://github.com/web-infra-dev/rspack/pull/3567

**Closed by underfin** 2023-06-29 09:02 UTC
Labels: bug, team
