### ISSUE TITLE
Add support for topLevelAwait option in experiments

### ISSUE THREAD

**Issue by KrzysztofZawisla** [web-infra-dev/rspack#3493] opened 2023-06-09 07:27 UTC
### What problem does this feature solve?

Adds compatibility to topLevelAwait option from wepback

### What does the proposed API of configuration look like?

```ts
const config = {
  experiments: {
    topLevelAwait: true,
  },
};
```

**Comment by hyf0** [comment] 2023-06-12 04:26
This issue blocks migration of following Webpack tests

- https://github.com/webpack/webpack/blob/main/test/configCases/graph/issue-11770/webpack.config.js

**Comment by hardfist** [comment] 2023-08-10 11:38
duplicate of #3889

**Closed by hardfist** 2023-08-10 11:38 UTC
Labels: feat, p3-nice-to-have
