### ISSUE TITLE
hexoid crashes if imported using commonjs

### ISSUE THREAD

**Issue by antoinepairet** [web-infra-dev/rspack#3240] opened 2023-05-21 10:05 UTC
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 404.19 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 8.19.2 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Edge: 113.0.1774.35
    Safari: 16.4
  npmPackages:
    @rspack/cli: 0.1.11 => 0.1.11 
    @rspack/core: 0.1.11 => 0.1.11 
    @rspack/dev-server: ~0.1.0 => 0.1.11 
    @rspack/plugin-minify: ~0.1.0 => 0.1.11

### Details

https://www.npmjs.com/package/hexoid is delivered as:

CommonJS: [dist/index.js](https://unpkg.com/hexoid/dist/index.js)
ES Module: [dist/index.mjs](https://unpkg.com/hexoid/dist/index.mjs)
UMD: [dist/index.min.js](https://unpkg.com/hexoid/dist/index.min.js)

When it is consumed through `CommonJS`, it crashes at runtime.
When it is consumed through `EMS`, it works fine

## Compilation output

ESM
````js
(function() {
var __webpack_modules__ = {
"56": function (module, exports, __webpack_require__) {
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "default", {
    enumerable: true,
    get: function() {
        return _default;
    }
});
var IDX = 256, HEX = [];
while(IDX--)HEX[IDX] = (IDX + 256).toString(16).substring(1);
function _default(len) {
    len = len || 16;
    var str = '', num = 0;
    return function() {
        if (!str || num === 256) {
            str = '';
            num = (1 + len) / 2 | 0;
            while(num--)str += HEX[256 * Math.random() | 0];
            str = str.substring(num = 0, len - 2);
        }
        return str + HEX[num++];
    };
}
},
"821": function (module, exports, __webpack_require__) {
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
var _56 = __webpack_require__.ir(__webpack_require__("56"));
const toID = (0, _56.default)();
toID();
},

}
````

CommonJS
````js
var __webpack_modules__ = {
"56": function (module, exports, __webpack_require__) {
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "default", {
    enumerable: true,
    get: function() {
        return _default;
    }
});
var IDX = 256, HEX = [];
while(IDX--)HEX[IDX] = (IDX + 256).toString(16).substring(1);
function _default(len) {
    len = len || 16;
    var str = '', num = 0;
    return function() {
        if (!str || num === 256) {
            str = '';
            num = (1 + len) / 2 | 0;
            while(num--)str += HEX[256 * Math.random() | 0];
            str = str.substring(num = 0, len - 2);
        }
        return str + HEX[num++];
    };
}
},
"821": function (module, exports, __webpack_require__) {
const hexoid = __webpack_require__("56");
const toID = hexoid();
toID();
},

}
````

### Reproduce Steps

This will crash at runtime:
````ts
const hexoid = require('hexoid');

const toID = hexoid();
toID(); //=> '52032fedb951da00'
````

This works
````ts
import hexoid from 'hexoid';

const toID = hexoid();
toID(); //=> '52032fedb951da00'
````

**Comment by hardfist** [comment] 2023-05-22 05:57
actually both of the import | require are bundling the module entrypoint(dist/index.mjs), and since dist/index.mjs only exports default, so you need to do 
```js
const hexoid = require('hexoid').default
```
this is the same behavior as webpack, and you can check the source code here https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1259.
I'm not sure whether default behavior is right, since esbuild takes another approach( main over module when target = node). @alexander-akait may know why webpack design this way.

**Comment by antoinepairet** [comment] 2023-05-22 07:56
Thanks for the fast reply @hardfist 

Webpack and Rspack behave differently. The compiled code does not crash at runtime when built using Webpack.
My understanding is that Rspack bundles the module entrypoint(dist/index.mjs) while webpack uses the common js one (dist/index.js).

Webpack output:
````js
/******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ([
/* 0 */,
/* 1 */
/***/ ((module) => {

var IDX=256, HEX=[];
while (IDX--) HEX[IDX] = (IDX + 256).toString(16).substring(1);

module.exports = function (len) {
	len = len || 16;
	var str='', num=0;
	return function () {
		if (!str || num === 256) {
			str=''; num=(1+len)/2 | 0;
			while (num--) str += HEX[256 * Math.random() | 0];
			str = str.substring(num=0, len-2);
		}
		return str + HEX[num++];
	};
}


/***/ })
/******/ 	]);
````

Rspack:
````js
var __webpack_modules__ = {
"56": function (module, exports, __webpack_require__) {
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "default", {
    enumerable: true,
    get: function() {
        return _default;
    }
});
var IDX = 256, HEX = [];
while(IDX--)HEX[IDX] = (IDX + 256).toString(16).substring(1);
function _default(len) {
    len = len || 16;
    var str = '', num = 0;
    return function() {
        if (!str || num === 256) {
            str = '';
            num = (1 + len) / 2 | 0;
            while(num--)str += HEX[256 * Math.random() | 0];
            str = str.substring(num = 0, len - 2);
        }
        return str + HEX[num++];
    };
}
},
"821": function (module, exports, __webpack_require__) {
const hexoid = __webpack_require__("56");
const toID = hexoid();
console.log(toID());
},

}
````

**Comment by hardfist** [comment] 2023-05-22 07:58
@antoinepairet  what webpack version do you use?

**Comment by hardfist** [comment] 2023-05-22 07:59
https://github.com/web-infra-dev/rspack-repro maybe you can provide demo using rspack repro template, so we can compare the result of rspack and webpack

**Comment by alexander-akait** [comment] 2023-05-22 12:27
Does rspack support https://github.com/lukeed/hexoid/blob/master/package.json#L6? Based on output rspack takes ESM version, but when you use `const hexoid = require('hexoid');` we should take commonjs version (webpack takes it)

**Comment by hardfist** [comment] 2023-05-22 12:39
> Does rspack support https://github.com/lukeed/hexoid/blob/master/package.json#L6? Based on output rspack takes ESM version, but when you use `const hexoid = require('hexoid');` we should take commonjs version (webpack takes it)

we support exports field but hexiod doesnt use exports field https://www.npmjs.com/package/hexoid?activeTab=code

**Comment by hardfist** [comment] 2023-05-22 12:40
it seems packagejson is the same between github and npm

**Comment by antoinepairet** [comment] 2023-05-22 14:51
> it seems packagejson is the same between github and npm

You probably meant "NOT the same"

https://www.npmjs.com/package/hexoid?activeTab=code does not use `exports` field in `package.json`
while https://github.com/lukeed/hexoid/blob/master/package.json#L6 has it

Rspack and webpack behave differently in this case.

**Comment by alexander-akait** [comment] 2023-05-22 16:18
The difference between webpack and rspack is that rpack uses the ESM version and webpack uses commonjs, because there is no `exports` in published package, I see only these things:
```
"module": "dist/index.mjs",
"main": "dist/index.js",
```

So my question - @antoinepairet What is the target - `node` or `web`?

**Comment by antoinepairet** [comment] 2023-05-22 19:04
Rspack breaks when all dependencies are bundled: `config.externals = []`.

The reproduction scenario is available here: https://github.com/rosahealth/rspack-is-awesome

It is an Nx workspace with 1 project and 3 configs to build or serve the project:
- using Rspack without `config.externals`
- using Rspack with `config.externals`
- using webpack

````
➜  rspack-is-awesome git:(main) ✗ diff rspack.config.js rspack.broken-config.js
9a10,11
>   config.externals = []; // <-- This is what makes it crash at runtime
> 
➜  rspack-is-awesome git:(main) 
````


Here is the content of `rspack.broken-config.js` (@alexander-akait the target is `node`):
````js
const { composePlugins, withNx } = require('@nrwl/rspack');

module.exports = composePlugins(withNx(), (config) => {
  config.devtool = false;
  config.optimization = {
    ...config.optimization,
    minimize: false,
  };

  config.externals = []; // <-- This is what makes it crash at runtime

  config.target = ['node', 'es2015'];
  config.output = {
    ...config.output,
    chunkFormat: 'commonjs',
  };

  return config;
});
````

Let me know if you need more info.

**Comment by hardfist** [comment] 2023-05-22 22:16
@antoinepairet your demo is kind of too complex, so I made the minimal demo using rspack-repro template https://github.com/hardfist/rspack-webpack-crash, and you can see both rspack and webpack result crash at runtime.
![image](https://github.com/web-infra-dev/rspack/assets/8898718/8f15ed4f-50cf-443c-867c-b170ad154513)
so rspack and webpack behaves the same way

**Comment by hardfist** [comment] 2023-05-22 22:22
> The difference between webpack and rspack is that rpack uses the ESM version and webpack uses commonjs, because there is no `exports` in published package, I see only these things:
> 
> ```
> "module": "dist/index.mjs",
> "main": "dist/index.js",
> ```
> 
> So my question - @antoinepairet What is the target - `node` or `web`?
@alexander-akait  webpack will also pick the module field over main field even when target set to node, am I wrong?

**Comment by alexander-akait** [comment] 2023-05-22 22:31
Our logic:
 - for web (and web related) targets - `["browser", "module", "main"]`
 - for node `["module", "main"]`
 
 So yes

**Comment by antoinepairet** [comment] 2023-05-23 06:11
@alexander-akait @hardfist Thank you for the follow-up 🙌🏻 
Next time I will create the reproduction using the rspack template 👍🏻 

I will create an issue on the `hexoid` repo to add the `exports` in the `package.json` on `npm`.

**Comment by hardfist** [comment] 2023-05-23 07:04
> @alexander-akait @hardfist Thank you for the follow-up 🙌🏻 Next time I will create the reproduction using the rspack template 👍🏻
> 
> I will create an issue on the `hexoid` repo to add the `exports` in the `package.json` on `npm`.

since it's not a bug of rspack, gonna close the issue

**Closed by hardfist** 2023-05-23 07:04 UTC
Labels: bug, same as webpack
