### ISSUE TITLE
[Bug Report]: webpack-dev-middleware "panicked at 'Module should be added before'"

### ISSUE THREAD

**Issue by AngusFu** [web-infra-dev/rspack#2572] opened 2023-03-31 11:22 UTC
### System Info

```
 System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 104.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 104.0.2
    Safari: 16.0
  npmPackages:
    @rspack/cli: latest => 0.1.4 
```

### Details

I get the following error during development by just removing a import declaration(which imports a simple demo component copied from ant design docs).

![image](https://user-images.githubusercontent.com/8180186/229107213-6b2a4e6d-1626-48cb-9ea3-42138a671ba3.png)

```
Rspack ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 10% building ./App                                                                                                                   <e> [webpack-dev-middleware] [Error: error[internal]: Module should be added before.
<e> Raw: panicked at 'Module should be added before', /Users/runner/work/rspack/rspack/crates/rspack_core/src/chunk_graph.rs:163:8
<e> This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.
<e> 
<e>    0: _napi_register_module_v1
<e>    1: <unknown>
<e>    2: _napi_register_module_v1
<e>    3: _napi_register_module_v1
<e>    4: _napi_register_module_v1
<e>    5: _napi_register_module_v1
<e>    6: _napi_register_module_v1
<e>    7: _napi_register_module_v1
<e>    8: _napi_register_module_v1
<e>    9: _napi_register_module_v1
<e>   10: <unknown>
<e>   11: <unknown>
<e>   12: <unknown>
<e>   13: <unknown>
<e>   14: <unknown>
<e>   15: <unknown>
<e>   16: <unknown>
<e>   17: <unknown>
<e>   18: <unknown>
<e>   19: <unknown>
<e>   20: <unknown>
<e>   21: <unknown>
<e>   22: <unknown>
<e>   23: _napi_register_module_v1
<e>   24: _napi_register_module_v1
<e>   25: _napi_register_module_v1
<e>   26: _napi_register_module_v1
<e>   27: <unknown>
<e>   28: <unknown>
<e>   29: <unknown>
<e>   30: _napi_register_module_v1
<e>   31: _napi_register_module_v1
<e>   32: _napi_register_module_v1
<e>   33: _napi_register_module_v1
<e>   34: __pthread_deallocate
<e> 
<e> ] {
<e>   code: 'GenericFailure'
<e> }
```

### Reproduce link

https://github.com/AngusFu/rspack-issue-reproduction

### Reproduce Steps

1. Initialize the project: `npm create rspack@latest && cd rspack-project && npm i`
2. Install `antd` in the project: `npm i antd`
3. Create `src/Demo.tsx`, and paste some snippet from ant-design official site, for example
```jsx
import React from "react";
import Button from "antd/es/button";
import Space from "antd/es/space";

const Demo: React.FC = () => (
  <Space wrap>
    <Button type="primary">Primary Button</Button>
    <Button>Default Button</Button>
    <Button type="dashed">Dashed Button</Button>
    <Button type="text">Text Button</Button>
    <Button type="link">Link Button</Button>
  </Space>
);

export default Demo;
```
4. Add `import Demo from './Demo'` in `src/App.js`
5. Run `npm run dev`
6. Remove the import declaration added in **STEP 4**
7. Oooooooops!

**Comment by hyf0** [comment] 2023-04-19 07:45
I could not reproduce the problem either using `0.1.4` or `0.1.8`.

Please try to reproduce the problem using the current latest version `0.1.8` and re-open this issue if you could reproduce the problem.

**Comment by AngusFu** [comment] 2023-04-20 07:08
> I could not reproduce the problem either using `0.1.4` or `0.1.8`.
> 
> Please try to reproduce the problem using the current latest version `0.1.8` and re-open this issue if you could reproduce the problem.

@hyf0 Indeed the problem described above now disappears. However, I got another error which looks similar to the original issue: 

![image](https://user-images.githubusercontent.com/8180186/233285733-7ae0900d-e63b-42cc-88eb-368b32ecda66.png)

System Info:

```
  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 182.81 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Firefox: 104.0.2
    Safari: 16.0
  npmPackages:
    @rspack/cli: latest => 0.1.8 
```

I will find another laptop and try again. Just wait for my reply.

**Comment by AngusFu** [comment] 2023-04-20 07:24
### Update

I tried the reproduction repo with docker image `node:16.15.1`,  and got the  same error: 

![image](https://user-images.githubusercontent.com/8180186/233290934-ffd5c6f6-1cee-42fe-a2ff-d5de058dd9cb.png)


```
  System:
    OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) arm64 unknown
    Memory: 6.67 GB / 7.67 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  npmPackages:
    @rspack/cli: latest => 0.1.8 
```

**Comment by hyf0** [comment] 2023-04-20 07:26
Thanks. I would keep invesgating.

**Comment by AngusFu** [comment] 2023-04-25 04:51
### Update 4

I accidentally used v0.0.18 and found the problem did not occur. So I tested v0.0.25, v0.0.20, v0.0.23, v0.0.24,  and found that in the `v0.0.x` series, **v0.0.23 is the last version that would NOT BREAK**.

Hope this may bring you some clue on resolving this issue.







[0.0.23](https://www.npmjs.com/package/@rspack/cli/v/0.0.23)

**Comment by hyf0** [comment] 2023-04-25 07:14
Which package you are referring to for the version about`v0.0.25, v0.0.20, v0.0.23, v0.0.24`?

If `@rspack/cli@0.0.18` solve the problem, I would close this issue and not investigate anymore.

**Comment by AngusFu** [comment] 2023-04-25 08:13
@hyf0  Of course `v0.0.23` refers to `@rspack/cli@0.0.23`. (Seems the dependencies of `@rspack/cli` under `@rspack` scope get the same version with `@rspack/cli`)

My latest reply was just providing a possible clue for you guys to investigate the issue.  Maybe you can investigate what's changed  between the `0.0.23` and `0.0.24` releases (though it's a hard work, I know). 

As far as I see,  my problem is **NOT solved**,  maybe it cannot be solved in a short time. So feel free to close this issue, or label it as "delay" or something else. 

----

我并不认为我的问题因此解决了。

我只是提供一个 debug 的线索，也许看看从 0.0.23 到 0.0.24 之间发生了什么能够有助于发现问题（虽然可能工作量也挺大）。

不过我个人感觉，这个问题可能短期内也不太可能解决吧。（看报错，应该是依赖过于复杂的场景下， chunk graph 变化时出问题了。可惜我 rust 不太行）

**Comment by AngusFu** [comment] 2023-04-26 06:07
@hyf0 

After some deep hard/clumsy investigation (debugging with `rspack` source code),  I believe it's **circular dependencies**(循环依赖) in `antd` (which was used in my reproduction repo) that caused this problem. 

I dumped `self.module_graph.connections` in `crates/rspack_core/src/compiler/compilation.rs`,  and found the following circular dependencies: 

![image](https://user-images.githubusercontent.com/8180186/234482168-8fa4f9ff-e11c-4304-8f18-18f449e7136a.png)

Then I manually modified those files in node_modules, and it works!

## Minimal Reproduction

I've [updated](https://github.com/AngusFu/rspack-issue-reproduction/commit/a6c9472f72ae3c7de673d9ccb0f0b44837d62a6e) the reproduction repo with a minimal case. Turns out it breaks too.

![image](https://user-images.githubusercontent.com/8180186/234483403-dbba9a1b-1a3c-4c03-8270-b5f5cb7b3b6f.png)
![image](https://user-images.githubusercontent.com/8180186/234483708-e7a7d4fb-7272-453e-aa67-6205f845cc91.png)

**Comment by hyf0** [comment] 2023-04-26 08:03
Good job! Thanks for investigating deeply. I try to fix this this week. 

@jerrykingxyz cc. in case you are interested in this

**Comment by AngusFu** [comment] 2023-04-26 08:57
Due to circular dependencies,  current **clean_queue** tasks would not clear `Demo.tsx` when HMR. We can still find `Demo.tsx` in module_graph even though the import declaration is removed.

> Key steps for **clean_queue**: 
> 1. hmr.rs: `self.compile(setup_make_params).await?;`
> 2. mod.rs: `self.compilation.make(params).await?;`
> 3. compilation.rs: `while let Some(task) = clean_queue.get_task()`

Then in the **seal** process (`self.compilation.seal(self.plugin_driver.clone()).await?;`),   new compilation's chunk_graph is mutated. Since the import of `Demo.tsx` is removed, the chunk turns to `None`. 

When calling `collect_changed_modules()` with new compilation,  `.expect("should has module id")` would fail.

---- 

因循环依赖的存在，HMR 时 **clean_queue**  操作后，`Demo.tsx` 仍会保留在 module_graph 中（尽管我们注释掉了 import 语句）。

接下来是 `seal` 操作(`self.compilation.seal(self.plugin_driver.clone()).await?;`)，new compilation's 的  chunk_graph 发生了变更（更准确的说法是，seal 前 chunk_graph 是空的，seal 后就没了 `Demo.tsx` 的部分）。

所以，`hmr.rs` 中第二次调用 `collect_changed_modules()` 时，会触发  `.expect("should has module id")` 这个报错。

**Comment by AngusFu** [comment] 2023-04-26 08:59
BTW,  a syntax error in `hmr.rs` (`.expect("should has module id") `) 🐶 🐶 🐶 : 

`should has` => `should have` (or  `Module id expected`)

**Comment by jerrykingxyz** [comment] 2023-04-27 03:04
Thanks for your investigation, the clean_queue cannot remove circularly dependent modules is expected behavior. The reason is
1. A thorough cleanup algorithm will take a long time
2. Keeping useless modules may increase `make` speed when users reuse them

So there are two ways to fix them:
1. It is stipulated that not all modules are used in the chunk graph, fix `hmr.rs` (we can also delete clean_queue)
2. Use a thorough cleaning algorithm

I think the first one is more suitable, @hardfist @h-a-n-a cc

**Comment by Oussidi1998** [comment] 2023-04-28 13:41
I just did the migration to latest version `0.1.9` and I'm still getting the same error any updates regarding the issue?

**Comment by jerrykingxyz** [comment] 2023-05-04 03:02
I will fix it soon, you can disable incrementalRebuild with workaround(disable will make rebuild slower)
``` js
module.export = {
  experiments: {
    incrementalRebuild: false
  }
}
```

**Closed** 2023-05-05 06:39 UTC
Labels: bug, p2-signifincant
